import { StyleSheet } from "react-native";
import { spacing, screenPadding, type, radius } from "./typography";

export function createBookStyles(screenWidth: number) {
  const inner = screenWidth - screenPadding * 2;
  const dateChipW = (inner - spacing.sm * 2) / 3;
  const timeChipW = (inner - spacing.sm * 4) / 3;
  const svcCardW = (inner - spacing.md * 2) / 3.15;

  return StyleSheet.create({
    root: { flex: 1 },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: screenPadding,
      paddingBottom: spacing.md,
      borderBottomWidth: 1,
      gap: spacing.sm,
    },
    iconBtn: {
      width: 44,
      height: 44,
      borderRadius: radius.md,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
    },
    headerCenter: { flex: 1, alignItems: "center" },
    headerTitle: { ...type.title, fontSize: 17 },
    steps: { flexDirection: "row", gap: spacing.md, marginTop: spacing.sm },
    stepItem: { alignItems: "center", gap: 3 },
    stepDot: {
      width: 24,
      height: 24,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
    },
    stepNum: { ...type.step, color: "#fff" },
    stepLabel: { ...type.step },
    badge: {
      position: "absolute",
      top: 6,
      right: 6,
      backgroundColor: "#10b981",
      width: 16,
      height: 16,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    badgeText: { color: "#fff", fontSize: 9, fontWeight: "800" },
    scroll: {
      paddingHorizontal: screenPadding,
      paddingTop: spacing.lg,
      paddingBottom: spacing.md,
    },
    locBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.sm,
      padding: spacing.lg,
      borderRadius: radius.lg,
      borderWidth: 1,
      marginBottom: spacing.lg,
    },
    locText: { flex: 1, ...type.bodyBold, fontSize: 14 },
    svcStrip: { gap: spacing.md, paddingBottom: spacing.lg },
    svcCard: {
      width: svcCardW,
      height: 136,
      borderRadius: radius.xl,
      alignItems: "center",
      justifyContent: "center",
      padding: spacing.md,
      overflow: "hidden",
    },
    svcIcon: {
      width: 60,
      height: 60,
      borderRadius: radius.lg,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: spacing.sm,
    },
    svcImg: { width: 48, height: 48 },
    svcName: { ...type.chip, fontWeight: "800" },
    svcPrice: { ...type.chipSm },
    hero: {
      borderRadius: radius.xl,
      padding: spacing.xl,
      flexDirection: "row",
      alignItems: "center",
      marginBottom: spacing.xl,
      overflow: "hidden",
    },
    heroImg: { width: 96, height: 96 },
    heroText: { flex: 1, marginLeft: spacing.sm },
    bestSeller: {
      alignSelf: "flex-start",
      backgroundColor: "#059669",
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
      borderRadius: radius.pill,
      marginBottom: spacing.sm,
    },
    bestSellerText: { color: "#fff", ...type.overline },
    heroTitle: { color: "#fff", ...type.title, fontSize: 20 },
    heroSub: { color: "rgba(255,255,255,0.78)", ...type.small, marginTop: spacing.xs },
    ratingRow: { flexDirection: "row", alignItems: "center", gap: spacing.xs, marginTop: spacing.sm },
    ratingText: { color: "rgba(255,255,255,0.92)", ...type.small, fontWeight: "600" },
    pkgCard: {
      borderRadius: radius.xl,
      padding: spacing.lg,
      marginBottom: spacing.md,
    },
    popularBadge: {
      position: "absolute",
      top: spacing.md,
      right: spacing.md,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.xs,
      borderRadius: radius.pill,
    },
    popularText: { color: "#fff", ...type.overline, fontSize: 9 },
    pkgName: { ...type.title, fontSize: 17 },
    pkgTag: { ...type.small, marginTop: 2 },
    pkgPrice: { ...type.priceLg, marginVertical: spacing.sm },
    pkgItem: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginBottom: spacing.xs },
    pkgItemText: { ...type.small, flex: 1 },
    selectPill: {
      marginTop: spacing.md,
      paddingVertical: spacing.md,
      borderRadius: radius.lg,
      alignItems: "center",
    },
    selectPillText: { ...type.bodyBold, fontSize: 14 },
    chipRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginBottom: spacing.md },
    dateChip: {
      width: dateChipW,
      paddingVertical: spacing.md,
      borderRadius: radius.lg,
      alignItems: "center",
    },
    dateChipDay: { ...type.chip },
    dateChipDate: { ...type.chipSm, marginTop: 2 },
    timeChip: {
      width: timeChipW,
      paddingVertical: spacing.md,
      borderRadius: radius.lg,
      alignItems: "center",
    },
    timeChipText: { ...type.chipSm, fontWeight: "700" },
    slotBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.sm,
      padding: spacing.md,
      borderRadius: radius.lg,
      marginBottom: spacing.lg,
    },
    slotBannerText: { ...type.small, fontWeight: "600", flex: 1 },
    scheduleActions: { flexDirection: "row", gap: spacing.sm, marginBottom: spacing.md },
    scheduleActionBtn: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: spacing.sm,
      paddingVertical: spacing.md,
      borderRadius: radius.lg,
      borderWidth: 1,
    },
    manualRow: { flexDirection: "row", gap: spacing.sm, marginBottom: spacing.md },
    manualField: { flex: 1 },
    manualLabel: { ...type.caption, marginBottom: 4 },
    manualInput: {
      borderWidth: 1,
      borderRadius: radius.lg,
      paddingHorizontal: spacing.md,
      paddingVertical: spacing.md,
      ...type.body,
      fontVariant: ["tabular-nums"],
    },
    iosModalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.45)",
      justifyContent: "flex-end",
    },
    iosModalSheet: {
      borderTopLeftRadius: radius.xl,
      borderTopRightRadius: radius.xl,
      paddingBottom: spacing.xl,
    },
    iosModalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      borderBottomWidth: StyleSheet.hairlineWidth,
    },
    iosModalBtn: { paddingVertical: spacing.sm, paddingHorizontal: spacing.sm },
    aiCard: { borderRadius: radius.xl, padding: spacing.lg, marginBottom: spacing.lg },
    aiHeader: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginBottom: spacing.sm },
    aiTitle: { ...type.bodyBold, fontSize: 16 },
    aiBody: { ...type.small, marginBottom: spacing.sm },
    aiBtn: { padding: spacing.lg, borderRadius: radius.lg, alignItems: "center" },
    aiBtnText: { ...type.bodyBold },
    addonRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing.md,
      padding: spacing.lg,
      borderRadius: radius.lg,
      borderWidth: 1,
      marginBottom: spacing.sm,
    },
    addonTitle: { ...type.bodyBold },
    addonDesc: { ...type.caption, marginTop: 2 },
    addonPrice: { ...type.chip, color: "#059669", fontWeight: "800" },
    checkbox: {
      width: 24,
      height: 24,
      borderRadius: radius.sm,
      borderWidth: 2,
      alignItems: "center",
      justifyContent: "center",
    },
    input: {
      minHeight: 96,
      borderRadius: radius.lg,
      borderWidth: 1,
      padding: spacing.lg,
      textAlignVertical: "top",
      ...type.body,
      marginBottom: spacing.lg,
    },
    summary: {
      borderRadius: radius.xl,
      borderWidth: 1,
      padding: spacing.lg,
      marginTop: spacing.sm,
    },
    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: spacing.sm,
    },
    summaryLabel: { ...type.small },
    summaryValue: { ...type.bodyBold },
    totalRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderTopWidth: 1,
      paddingTop: spacing.md,
      marginTop: spacing.sm,
    },
    totalLabel: { ...type.bodyBold, fontSize: 16 },
    totalValue: { ...type.price },
    secure: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginTop: spacing.md },
    secureText: { ...type.caption, flex: 1 },
    footer: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: screenPadding,
      paddingVertical: spacing.md,
      borderTopWidth: 1,
      paddingBottom: spacing.xl,
    },
    footerLabel: { ...type.caption },
    footerTotal: { ...type.price },
    scrollSpacer: { height: 96 },
  });
}
