import type { AiToolStatus } from "@prisma/client";
import type { ToolRegistryEntry } from "../types";
import { PHASE16_AGENT_TOOLS } from "./phase16-agent-tools";

/** Built-in enterprise tool catalog — synced to ai_tool_registry on seed. */
export const TOOL_CATALOG: Omit<ToolRegistryEntry, "handler">[] = [
  // ── Customer Read Tools ──
  {
    toolId: "read.customer.getBooking",
    name: "getBooking",
    description: "Retrieve a single booking for the authenticated customer",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.customer.booking",
    requiredRole: "CUSTOMER",
    requiredPolicy: "customer.ownership",
    riskLevel: "LOW",
    parameters: [
      { name: "bookingId", type: "string", required: true, description: "Booking ID" },
    ],
    validationSchema: { type: "object", required: ["bookingId"], properties: { bookingId: { type: "string", minLength: 1 } } },
    timeoutMs: 10_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "booking.service.getForUser",
    eventMapping: "homigo.ai.tool.read",
    metricsKey: "get_booking",
    costEstimateUsd: 0.0001,
    owner: "platform-booking",
    status: "ACTIVE",
  },
  {
    toolId: "read.customer.getBookingStatus",
    name: "getBookingStatus",
    description: "Get current status of a customer booking",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.customer.booking",
    requiredRole: "CUSTOMER",
    requiredPolicy: "customer.ownership",
    riskLevel: "LOW",
    parameters: [{ name: "bookingId", type: "string", required: true, description: "Booking ID" }],
    validationSchema: { type: "object", required: ["bookingId"], properties: { bookingId: { type: "string" } } },
    timeoutMs: 8_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "booking.service.getForUser",
    metricsKey: "get_booking_status",
    costEstimateUsd: 0.0001,
    owner: "platform-booking",
    status: "ACTIVE",
  },
  {
    toolId: "read.customer.getBookings",
    name: "getBookings",
    description: "List bookings for the authenticated customer",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.customer.booking",
    requiredRole: "CUSTOMER",
    requiredPolicy: "customer.self",
    riskLevel: "LOW",
    parameters: [
      { name: "page", type: "number", required: false, description: "Page number" },
      { name: "limit", type: "number", required: false, description: "Page size" },
      { name: "status", type: "string", required: false, description: "Filter by status" },
    ],
    validationSchema: { type: "object", properties: { page: { type: "number" }, limit: { type: "number" }, status: { type: "string" } } },
    timeoutMs: 15_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "booking.service.listForUser",
    metricsKey: "get_bookings",
    costEstimateUsd: 0.0002,
    owner: "platform-booking",
    status: "ACTIVE",
  },
  {
    toolId: "read.customer.getWallet",
    name: "getWallet",
    description: "Get wallet balance for the authenticated customer",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.customer.wallet",
    requiredRole: "CUSTOMER",
    requiredPolicy: "customer.self",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 8_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "wallet.service.balance",
    metricsKey: "get_wallet",
    costEstimateUsd: 0.0001,
    owner: "platform-finance",
    status: "ACTIVE",
  },
  {
    toolId: "read.customer.getWalletTransactions",
    name: "getWalletTransactions",
    description: "List wallet transactions for the authenticated customer",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.customer.wallet",
    requiredRole: "CUSTOMER",
    requiredPolicy: "customer.self",
    riskLevel: "LOW",
    parameters: [
      { name: "page", type: "string", required: false, description: "Page" },
      { name: "limit", type: "string", required: false, description: "Limit" },
    ],
    validationSchema: { type: "object" },
    timeoutMs: 12_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "wallet.service.transactions",
    metricsKey: "get_wallet_transactions",
    costEstimateUsd: 0.0002,
    owner: "platform-finance",
    status: "ACTIVE",
  },
  {
    toolId: "read.customer.getSubscription",
    name: "getSubscription",
    description: "Get active subscription for the authenticated customer",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.customer.subscription",
    requiredRole: "CUSTOMER",
    requiredPolicy: "customer.self",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 8_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "subscription.service.mine",
    metricsKey: "get_subscription",
    costEstimateUsd: 0.0001,
    owner: "platform-membership",
    status: "ACTIVE",
  },
  {
    toolId: "read.customer.getServices",
    name: "getServices",
    description: "Browse available services catalog",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.customer.catalog",
    requiredRole: "CUSTOMER",
    requiredPolicy: "public.read",
    riskLevel: "LOW",
    parameters: [
      { name: "category", type: "string", required: false, description: "Category filter" },
      { name: "city", type: "string", required: false, description: "City filter" },
    ],
    validationSchema: { type: "object" },
    timeoutMs: 10_000,
    maxRetries: 1,
    auditRequired: false,
    approvalRequired: false,
    serviceMapping: "catalog.service.list",
    metricsKey: "get_services",
    costEstimateUsd: 0.0001,
    owner: "platform-catalog",
    status: "ACTIVE",
  },
  {
    toolId: "read.customer.getOffers",
    name: "getOffers",
    description: "Get wallet offers and promotions",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.customer.offers",
    requiredRole: "CUSTOMER",
    requiredPolicy: "public.read",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 8_000,
    maxRetries: 1,
    auditRequired: false,
    approvalRequired: false,
    serviceMapping: "wallet.service.offers",
    metricsKey: "get_offers",
    costEstimateUsd: 0.0001,
    owner: "platform-finance",
    status: "ACTIVE",
  },

  // ── Partner Read Tools ──
  {
    toolId: "read.partner.getPartnerProfile",
    name: "getPartnerProfile",
    description: "Get partner profile and settings",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.partner.profile",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.self",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 10_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "provider.service.me",
    metricsKey: "get_partner_profile",
    costEstimateUsd: 0.0001,
    owner: "platform-partner",
    status: "ACTIVE",
  },
  {
    toolId: "read.partner.getPartnerJobs",
    name: "getPartnerJobs",
    description: "List partner job bookings",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.partner.jobs",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.self",
    riskLevel: "LOW",
    parameters: [
      { name: "page", type: "string", required: false, description: "Page" },
      { name: "status", type: "string", required: false, description: "Status filter" },
    ],
    validationSchema: { type: "object" },
    timeoutMs: 12_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "provider.service.myBookings",
    metricsKey: "get_partner_jobs",
    costEstimateUsd: 0.0002,
    owner: "platform-partner",
    status: "ACTIVE",
  },
  {
    toolId: "read.partner.getPartnerPerformance",
    name: "getPartnerPerformance",
    description: "Get partner performance intelligence",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.partner.performance",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.self",
    riskLevel: "LOW",
    parameters: [{ name: "days", type: "number", required: false, description: "Lookback days" }],
    validationSchema: { type: "object" },
    timeoutMs: 15_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "partnerOs.service.getProviderIntelligence",
    metricsKey: "get_partner_performance",
    costEstimateUsd: 0.0003,
    owner: "platform-partner",
    status: "ACTIVE",
  },
  {
    toolId: "read.partner.getPartnerEarnings",
    name: "getPartnerEarnings",
    description: "Get partner earnings summary",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.partner.earnings",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.self",
    riskLevel: "LOW",
    parameters: [{ name: "days", type: "number", required: false, description: "Lookback days" }],
    validationSchema: { type: "object" },
    timeoutMs: 12_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "provider.service.myEarningsSummary",
    metricsKey: "get_partner_earnings",
    costEstimateUsd: 0.0002,
    owner: "platform-partner",
    status: "ACTIVE",
  },
  {
    /**
     * Structured earnings-opportunity facts for a target amount.
     *
     * Distinct from `getPartnerEarnings`, which reports what has already been earned. This returns
     * the deterministic PLAN — realised vs target vs gap, jobs needed with a stated error, a
     * feasibility band against the partner's own record, ranked zones and evidenced time windows.
     *
     * Deliberately READ-only and LOW risk: the coach opens no transaction and moves no money. The
     * model consuming this may explain these facts; it must never compute them, which is why the
     * numbers arrive pre-computed with their sources attached.
     */
    toolId: "read.partner.getEarningsOpportunity",
    name: "getEarningsOpportunity",
    description: "Get a grounded earnings-opportunity plan for a target amount",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.partner.earnings",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.self",
    riskLevel: "LOW",
    parameters: [
      { name: "targetAmount", type: "number", required: true, description: "Target earnings in INR" },
    ],
    validationSchema: { type: "object" },
    timeoutMs: 15_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "earnings-coach.service.plan",
    metricsKey: "get_earnings_opportunity",
    costEstimateUsd: 0.0002,
    owner: "platform-partner",
    status: "ACTIVE",
  },
  {
    /**
     * Structured performance evidence for the authenticated partner.
     *
     * Returns every metric considered — including the ones that produced no nudge and why — so the
     * model can explain a result without re-deriving it. Each metric carries its definition,
     * sample sizes, both periods, the significance threshold it had to clear, and a confidence.
     *
     * READ-only and LOW risk: computation touches nothing and sends nothing.
     */
    toolId: "read.partner.getPerformanceNudges",
    name: "getPerformanceNudges",
    description: "Get evidence-backed performance nudges for the partner",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.partner.performance",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.self",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 15_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "performance-nudges.service.compute",
    metricsKey: "get_performance_nudges",
    costEstimateUsd: 0.0002,
    owner: "platform-partner",
    status: "ACTIVE",
  },
  {
    toolId: "read.partner.getPartnerDemand",
    name: "getPartnerDemand",
    description: "Get demand forecast for partner zone",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.partner.demand",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.self",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 15_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "partnerOs.service.getForecast",
    metricsKey: "get_partner_demand",
    costEstimateUsd: 0.0003,
    owner: "platform-partner",
    status: "ACTIVE",
  },
  {
    toolId: "read.partner.getPartnerSchedule",
    name: "getPartnerSchedule",
    description: "Get partner attendance and schedule",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.partner.schedule",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.self",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 10_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "partnerOs.service.getAttendance",
    metricsKey: "get_partner_schedule",
    costEstimateUsd: 0.0001,
    owner: "platform-partner",
    status: "ACTIVE",
  },
  {
    /**
     * Read-only payout *status* for the authenticated partner.
     *
     * Distinct from `high_risk.finance.payout`, which processes money and stays unbound.
     * Bank account numbers and gateway payout IDs are stripped in the handler.
     */
    toolId: "read.partner.getPartnerPayout",
    name: "getPartnerPayout",
    description: "Get payout and withdrawal status for the authenticated partner (no bank details)",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.partner.earnings",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.self",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 12_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "earnings.service.getPartnerFinanceCenter",
    metricsKey: "get_partner_payout",
    costEstimateUsd: 0.0002,
    owner: "platform-finance",
    status: "ACTIVE",
  },
  {
    toolId: "read.partner.getPartnerTraining",
    name: "getPartnerTraining",
    description: "Get Academy training progress for the authenticated partner",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.partner.profile",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.self",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 12_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "partnerOnboarding.service.getTraining",
    metricsKey: "get_partner_training",
    costEstimateUsd: 0.0001,
    owner: "platform-partner",
    status: "ACTIVE",
  },
  {
    toolId: "read.admin.getSupplyDemand",
    name: "getSupplyDemand",
    description: "Get zone demand, eligible supply, gap and skill-gap recommendations",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.admin.operations",
    requiredRole: "ADMIN",
    requiredPolicy: "admin.rbac",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 15_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "geoIntelligence.service.zoneScoring",
    metricsKey: "get_supply_demand",
    costEstimateUsd: 0.0003,
    owner: "platform-geo",
    status: "ACTIVE",
  },

  // ── Admin Read Tools ──
  {
    toolId: "read.admin.getProviders",
    name: "getProviders",
    description: "List service providers (admin)",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.admin.providers",
    requiredRole: "ADMIN",
    requiredPolicy: "admin.rbac",
    riskLevel: "LOW",
    parameters: [
      { name: "page", type: "string", required: false, description: "Page" },
      { name: "status", type: "string", required: false, description: "Status filter" },
    ],
    validationSchema: { type: "object" },
    timeoutMs: 15_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "admin.service.listProviders",
    metricsKey: "get_providers",
    costEstimateUsd: 0.0003,
    owner: "platform-admin",
    status: "ACTIVE",
  },
  {
    toolId: "read.admin.getCustomers",
    name: "getCustomers",
    description: "List customers (admin)",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.admin.customers",
    requiredRole: "ADMIN",
    requiredPolicy: "admin.rbac",
    riskLevel: "LOW",
    parameters: [
      { name: "page", type: "string", required: false, description: "Page" },
      { name: "search", type: "string", required: false, description: "Search query" },
    ],
    validationSchema: { type: "object" },
    timeoutMs: 15_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "admin.service.listUsers",
    metricsKey: "get_customers",
    costEstimateUsd: 0.0003,
    owner: "platform-admin",
    status: "ACTIVE",
  },
  {
    toolId: "read.admin.getRevenue",
    name: "getRevenue",
    description: "Get platform revenue analytics",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.admin.finance",
    requiredRole: "ADMIN",
    requiredPolicy: "admin.finance.read",
    riskLevel: "MEDIUM",
    parameters: [
      { name: "startDate", type: "string", required: false, description: "Start date ISO" },
      { name: "endDate", type: "string", required: false, description: "End date ISO" },
    ],
    validationSchema: { type: "object" },
    timeoutMs: 20_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "admin.service.analytics",
    metricsKey: "get_revenue",
    costEstimateUsd: 0.0005,
    owner: "platform-finance",
    status: "ACTIVE",
  },
  {
    toolId: "read.admin.getFinanceSummary",
    name: "getFinanceSummary",
    description: "Get finance dashboard overview",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.admin.finance",
    requiredRole: "ADMIN",
    requiredPolicy: "admin.finance.read",
    riskLevel: "MEDIUM",
    parameters: [{ name: "days", type: "number", required: false, description: "Period days" }],
    validationSchema: { type: "object" },
    timeoutMs: 20_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "financeDashboard.service.getOverview",
    metricsKey: "get_finance_summary",
    costEstimateUsd: 0.0005,
    owner: "platform-finance",
    status: "ACTIVE",
  },
  {
    toolId: "read.admin.getFraudSummary",
    name: "getFraudSummary",
    description: "Get fraud intelligence overview",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.admin.fraud",
    requiredRole: "ADMIN",
    requiredPolicy: "admin.fraud.read",
    riskLevel: "MEDIUM",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 15_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "fraudAdmin.service.overview",
    metricsKey: "get_fraud_summary",
    costEstimateUsd: 0.0004,
    owner: "platform-fraud",
    status: "ACTIVE",
  },
  {
    toolId: "read.admin.getForecast",
    name: "getForecast",
    description: "Get demand forecast (admin)",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.admin.analytics",
    requiredRole: "ADMIN",
    requiredPolicy: "admin.analytics.read",
    riskLevel: "LOW",
    parameters: [{ name: "horizonHours", type: "number", required: false, description: "Forecast horizon" }],
    validationSchema: { type: "object" },
    timeoutMs: 20_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "geoIntelligence.service.demandForecast",
    metricsKey: "get_forecast",
    costEstimateUsd: 0.0004,
    owner: "platform-analytics",
    status: "ACTIVE",
  },
  {
    toolId: "read.admin.getDemand",
    name: "getDemand",
    description: "Get demand intelligence KPIs",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.admin.analytics",
    requiredRole: "ADMIN",
    requiredPolicy: "admin.analytics.read",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 20_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "geoIntelligence.service.executiveKpis",
    metricsKey: "get_demand",
    costEstimateUsd: 0.0004,
    owner: "platform-analytics",
    status: "ACTIVE",
  },
  {
    toolId: "read.admin.getSupply",
    name: "getSupply",
    description: "Get provider supply density",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.admin.analytics",
    requiredRole: "ADMIN",
    requiredPolicy: "admin.analytics.read",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 20_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "geoIntelligence.service.providerDensity",
    metricsKey: "get_supply",
    costEstimateUsd: 0.0004,
    owner: "platform-analytics",
    status: "ACTIVE",
  },
  {
    toolId: "read.admin.getOperations",
    name: "getOperations",
    description: "Get operations dashboard summary",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.admin.operations",
    requiredRole: "ADMIN",
    requiredPolicy: "admin.rbac",
    riskLevel: "LOW",
    parameters: [],
    validationSchema: { type: "object" },
    timeoutMs: 15_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "admin.service.dashboard",
    metricsKey: "get_operations",
    costEstimateUsd: 0.0003,
    owner: "platform-ops",
    status: "ACTIVE",
  },

  // ── Common Read Tools ──
  {
    toolId: "read.common.getWeather",
    name: "getWeather",
    description: "Get weather snapshot by coordinates or city",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.common.weather",
    requiredRole: "CUSTOMER,PARTNER,ADMIN,SUPPORT",
    requiredPolicy: "public.read",
    riskLevel: "LOW",
    parameters: [
      { name: "lat", type: "number", required: false, description: "Latitude" },
      { name: "lng", type: "number", required: false, description: "Longitude" },
      { name: "city", type: "string", required: false, description: "City name" },
    ],
    validationSchema: { type: "object" },
    timeoutMs: 10_000,
    maxRetries: 2,
    auditRequired: false,
    approvalRequired: false,
    serviceMapping: "weather.service.getByCoords",
    metricsKey: "get_weather",
    costEstimateUsd: 0.0002,
    owner: "platform-geo",
    status: "ACTIVE",
  },
  {
    toolId: "read.common.getTraffic",
    name: "getTraffic",
    description: "Get ETA with traffic between two points",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.common.traffic",
    requiredRole: "CUSTOMER,PARTNER,ADMIN,SUPPORT",
    requiredPolicy: "public.read",
    riskLevel: "LOW",
    parameters: [
      { name: "fromLat", type: "number", required: true, description: "Origin latitude" },
      { name: "fromLng", type: "number", required: true, description: "Origin longitude" },
      { name: "toLat", type: "number", required: true, description: "Destination latitude" },
      { name: "toLng", type: "number", required: true, description: "Destination longitude" },
    ],
    validationSchema: { type: "object", required: ["fromLat", "fromLng", "toLat", "toLng"] },
    timeoutMs: 12_000,
    maxRetries: 2,
    auditRequired: false,
    approvalRequired: false,
    serviceMapping: "maps.service.eta",
    metricsKey: "get_traffic",
    costEstimateUsd: 0.0003,
    owner: "platform-geo",
    status: "ACTIVE",
  },
  {
    toolId: "read.common.getETA",
    name: "getETA",
    description: "Get estimated time of arrival",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.common.eta",
    requiredRole: "CUSTOMER,PARTNER,ADMIN,SUPPORT",
    requiredPolicy: "public.read",
    riskLevel: "LOW",
    parameters: [
      { name: "fromLat", type: "number", required: true, description: "Origin latitude" },
      { name: "fromLng", type: "number", required: true, description: "Origin longitude" },
      { name: "toLat", type: "number", required: true, description: "Destination latitude" },
      { name: "toLng", type: "number", required: true, description: "Destination longitude" },
    ],
    validationSchema: { type: "object", required: ["fromLat", "fromLng", "toLat", "toLng"] },
    timeoutMs: 12_000,
    maxRetries: 2,
    auditRequired: false,
    approvalRequired: false,
    serviceMapping: "maps.service.eta",
    metricsKey: "get_eta",
    costEstimateUsd: 0.0003,
    owner: "platform-geo",
    status: "ACTIVE",
  },
  {
    toolId: "read.common.getLocation",
    name: "getLocation",
    description: "Get latest tracking location for a booking",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.common.location",
    requiredRole: "CUSTOMER,PARTNER,ADMIN,SUPPORT",
    requiredPolicy: "booking.access",
    riskLevel: "LOW",
    parameters: [{ name: "bookingId", type: "string", required: true, description: "Booking ID" }],
    validationSchema: { type: "object", required: ["bookingId"] },
    timeoutMs: 10_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "tracking.service.getLatestLocation",
    metricsKey: "get_location",
    costEstimateUsd: 0.0002,
    owner: "platform-tracking",
    status: "ACTIVE",
  },
  {
    toolId: "read.common.getNotifications",
    name: "getNotifications",
    description: "List notifications for the authenticated user",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.common.notifications",
    requiredRole: "CUSTOMER,PARTNER,ADMIN,SUPPORT",
    requiredPolicy: "actor.self",
    riskLevel: "LOW",
    parameters: [
      { name: "page", type: "number", required: false, description: "Page" },
      { name: "limit", type: "number", required: false, description: "Limit" },
    ],
    validationSchema: { type: "object" },
    timeoutMs: 10_000,
    maxRetries: 1,
    auditRequired: false,
    approvalRequired: false,
    serviceMapping: "notification.service.list",
    metricsKey: "get_notifications",
    costEstimateUsd: 0.0001,
    owner: "platform-notifications",
    status: "ACTIVE",
  },
  {
    toolId: "read.common.getSupportTickets",
    name: "getSupportTickets",
    description: "List support tickets for the authenticated user",
    category: "READ",
    version: "1.0.0",
    requiredPermission: "tools.read.common.support",
    requiredRole: "CUSTOMER,PARTNER,ADMIN,SUPPORT",
    requiredPolicy: "actor.self",
    riskLevel: "LOW",
    parameters: [
      { name: "page", type: "string", required: false, description: "Page" },
      { name: "status", type: "string", required: false, description: "Status filter" },
    ],
    validationSchema: { type: "object" },
    timeoutMs: 12_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "supportTicket.service.listForUser",
    metricsKey: "get_support_tickets",
    costEstimateUsd: 0.0002,
    owner: "platform-support",
    status: "ACTIVE",
  },

  // ── Controlled Write Tools ──
  {
    toolId: "write.booking.createBooking",
    name: "createBooking",
    description:
      "Create a service booking in two calls. First call WITHOUT confirmedTotalPaise: nothing is booked and the server's total is returned. Tell the customer that total and ask them to confirm. Only after they agree, call again with confirmedTotalPaise set to the returned value.",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.customer.booking",
    requiredRole: "CUSTOMER",
    requiredPolicy: "customer.booking.create",
    riskLevel: "MEDIUM",
    parameters: [
      { name: "serviceId", type: "string", required: true, description: "Service ID" },
      { name: "scheduledDate", type: "string", required: true, description: "ISO datetime" },
      { name: "addressId", type: "string", required: true, description: "Address ID" },
      { name: "description", type: "string", required: false, description: "Notes" },
      { name: "couponCode", type: "string", required: false, description: "Coupon code" },
      {
        name: "confirmedTotalPaise",
        type: "number",
        required: false,
        description: "The total in paise the customer agreed to, exactly as returned by the first call. Omit on the first call.",
      },
    ],
    validationSchema: { type: "object", required: ["serviceId", "scheduledDate", "addressId"] },
    timeoutMs: 30_000,
    maxRetries: 0,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "booking.service.create",
    eventMapping: "homigo.booking.created",
    metricsKey: "create_booking",
    costEstimateUsd: 0.001,
    owner: "platform-booking",
    status: "ACTIVE",
  },
  {
    toolId: "write.booking.updateBooking",
    name: "updateBooking",
    description: "Update booking details (description, schedule)",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.customer.booking",
    requiredRole: "CUSTOMER",
    requiredPolicy: "customer.ownership",
    riskLevel: "MEDIUM",
    parameters: [
      { name: "bookingId", type: "string", required: true, description: "Booking ID" },
      { name: "scheduledDate", type: "string", required: false, description: "New schedule ISO" },
      { name: "description", type: "string", required: false, description: "Updated notes" },
    ],
    validationSchema: { type: "object", required: ["bookingId"] },
    timeoutMs: 20_000,
    maxRetries: 0,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "booking.service.update",
    eventMapping: "homigo.booking.updated",
    metricsKey: "update_booking",
    costEstimateUsd: 0.001,
    owner: "platform-booking",
    status: "ACTIVE",
  },
  {
    toolId: "write.booking.rescheduleBooking",
    name: "rescheduleBooking",
    description: "Reschedule an existing booking",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.customer.booking",
    requiredRole: "CUSTOMER",
    requiredPolicy: "customer.ownership",
    riskLevel: "MEDIUM",
    parameters: [
      { name: "bookingId", type: "string", required: true, description: "Booking ID" },
      { name: "scheduledDate", type: "string", required: true, description: "New schedule ISO" },
    ],
    validationSchema: { type: "object", required: ["bookingId", "scheduledDate"] },
    timeoutMs: 20_000,
    maxRetries: 0,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "booking.service.update",
    eventMapping: "homigo.booking.rescheduled",
    metricsKey: "reschedule_booking",
    costEstimateUsd: 0.001,
    owner: "platform-booking",
    status: "ACTIVE",
  },
  {
    toolId: "write.booking.cancelBooking",
    name: "cancelBooking",
    description: "Cancel a booking",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.customer.booking",
    requiredRole: "CUSTOMER",
    requiredPolicy: "customer.ownership",
    riskLevel: "MEDIUM",
    parameters: [
      { name: "bookingId", type: "string", required: true, description: "Booking ID" },
      { name: "reason", type: "string", required: false, description: "Cancellation reason" },
    ],
    validationSchema: { type: "object", required: ["bookingId"] },
    timeoutMs: 25_000,
    maxRetries: 0,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "booking.service.cancel",
    eventMapping: "homigo.booking.cancelled",
    metricsKey: "cancel_booking",
    costEstimateUsd: 0.001,
    owner: "platform-booking",
    status: "ACTIVE",
  },
  {
    toolId: "write.support.createSupportTicket",
    name: "createSupportTicket",
    description: "Create a support ticket",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.common.support",
    requiredRole: "CUSTOMER,PARTNER",
    requiredPolicy: "actor.self",
    riskLevel: "LOW",
    parameters: [
      { name: "subject", type: "string", required: true, description: "Ticket subject" },
      { name: "description", type: "string", required: true, description: "Ticket body" },
      { name: "category", type: "string", required: true, description: "Category" },
      { name: "bookingId", type: "string", required: false, description: "Related booking" },
    ],
    validationSchema: { type: "object", required: ["subject", "description", "category"] },
    timeoutMs: 15_000,
    maxRetries: 0,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "supportTicket.service.create",
    eventMapping: "homigo.support.ticket_created",
    metricsKey: "create_support_ticket",
    costEstimateUsd: 0.0005,
    owner: "platform-support",
    status: "ACTIVE",
  },
  {
    toolId: "write.support.closeSupportTicket",
    name: "closeSupportTicket",
    description: "Close a support ticket (admin/support)",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.admin.support",
    requiredRole: "ADMIN,SUPPORT",
    requiredPolicy: "admin.support.write",
    riskLevel: "MEDIUM",
    parameters: [
      { name: "ticketId", type: "string", required: true, description: "Ticket ID" },
      { name: "resolution", type: "string", required: true, description: "Resolution text" },
    ],
    validationSchema: { type: "object", required: ["ticketId", "resolution"] },
    timeoutMs: 15_000,
    maxRetries: 0,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "supportTicket.service.adminResolve",
    eventMapping: "homigo.support.ticket_resolved",
    metricsKey: "close_support_ticket",
    costEstimateUsd: 0.0005,
    owner: "platform-support",
    status: "ACTIVE",
  },
  {
    toolId: "write.wallet.redeemCoupon",
    name: "redeemCoupon",
    description: "Redeem a wallet coupon/offer",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.customer.wallet",
    requiredRole: "CUSTOMER",
    requiredPolicy: "customer.self",
    riskLevel: "MEDIUM",
    parameters: [{ name: "couponCode", type: "string", required: true, description: "Coupon code" }],
    validationSchema: { type: "object", required: ["couponCode"] },
    timeoutMs: 15_000,
    maxRetries: 0,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "wallet.service.redeemCoupon",
    eventMapping: "homigo.wallet.coupon_redeemed",
    metricsKey: "redeem_coupon",
    costEstimateUsd: 0.001,
    owner: "platform-finance",
    status: "ACTIVE",
  },
  {
    toolId: "write.notification.sendCustomerNotification",
    name: "sendCustomerNotification",
    description: "Send notification to a customer (admin/system)",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.admin.notification",
    requiredRole: "ADMIN,SYSTEM",
    requiredPolicy: "admin.notification.send",
    riskLevel: "MEDIUM",
    parameters: [
      { name: "userId", type: "string", required: true, description: "Target user ID" },
      { name: "title", type: "string", required: true, description: "Notification title" },
      { name: "message", type: "string", required: true, description: "Notification body" },
      { name: "type", type: "string", required: false, description: "Notification type" },
    ],
    validationSchema: { type: "object", required: ["userId", "title", "message"] },
    timeoutMs: 10_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "notification.service.createForUser",
    eventMapping: "homigo.notification.sent",
    metricsKey: "send_customer_notification",
    costEstimateUsd: 0.0003,
    owner: "platform-notifications",
    status: "ACTIVE",
  },
  {
    toolId: "write.notification.sendPartnerNotification",
    name: "sendPartnerNotification",
    description: "Send notification to a partner (admin/system)",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.admin.notification",
    requiredRole: "ADMIN,SYSTEM",
    requiredPolicy: "admin.notification.send",
    riskLevel: "MEDIUM",
    parameters: [
      { name: "userId", type: "string", required: true, description: "Partner user ID" },
      { name: "title", type: "string", required: true, description: "Notification title" },
      { name: "message", type: "string", required: true, description: "Notification body" },
    ],
    validationSchema: { type: "object", required: ["userId", "title", "message"] },
    timeoutMs: 10_000,
    maxRetries: 1,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "notification.service.createForUser",
    eventMapping: "homigo.notification.sent",
    metricsKey: "send_partner_notification",
    costEstimateUsd: 0.0003,
    owner: "platform-notifications",
    status: "ACTIVE",
  },
  {
    toolId: "write.partner.acceptJob",
    name: "acceptJob",
    description: "Partner accepts a job booking",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.partner.jobs",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.job.action",
    riskLevel: "MEDIUM",
    /**
     * `lat`/`lng` were removed here (P3-8): they had no consumer anywhere in the accept domain.
     * `bookingService.accept(providerId, id, eta?)` has no GPS parameters and never reads location;
     * `bookingAcceptSchema` accepts only `eta`; and the real partner app posts only `{ eta }`.
     * Partner GPS has its own established contract — `trackingLocationSchema` over
     * `/ws/tracking/:bookingId` — which is where the partner app genuinely publishes position.
     * Advertising them here let the model supply coordinates that were silently discarded (and,
     * before the handler fix, were being written into `eta` as a latitude).
     */
    parameters: [
      { name: "bookingId", type: "string", required: true, description: "Booking ID" },
    ],
    validationSchema: { type: "object", required: ["bookingId"] },
    timeoutMs: 20_000,
    maxRetries: 0,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "booking.service.accept",
    eventMapping: "homigo.booking.assigned",
    metricsKey: "accept_job",
    costEstimateUsd: 0.001,
    owner: "platform-partner",
    status: "ACTIVE",
  },
  {
    toolId: "write.partner.rejectJob",
    name: "rejectJob",
    description: "Partner rejects a job booking",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.partner.jobs",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.job.action",
    riskLevel: "MEDIUM",
    parameters: [
      { name: "bookingId", type: "string", required: true, description: "Booking ID" },
      { name: "reason", type: "string", required: false, description: "Rejection reason" },
    ],
    validationSchema: { type: "object", required: ["bookingId"] },
    timeoutMs: 15_000,
    maxRetries: 0,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "booking.service.reject",
    eventMapping: "homigo.booking.rejected",
    metricsKey: "reject_job",
    costEstimateUsd: 0.001,
    owner: "platform-partner",
    status: "ACTIVE",
  },
  {
    toolId: "write.partner.updateAvailability",
    name: "updateAvailability",
    description: "Partner toggles online/offline availability",
    category: "WRITE",
    version: "1.0.0",
    requiredPermission: "tools.write.partner.availability",
    requiredRole: "PARTNER",
    requiredPolicy: "partner.self",
    riskLevel: "LOW",
    parameters: [{ name: "online", type: "boolean", required: true, description: "Online status" }],
    validationSchema: { type: "object", required: ["online"] },
    timeoutMs: 10_000,
    maxRetries: 0,
    auditRequired: true,
    approvalRequired: false,
    serviceMapping: "provider.service.setOnline",
    eventMapping: "homigo.partner.online",
    metricsKey: "update_availability",
    costEstimateUsd: 0.0003,
    owner: "platform-partner",
    status: "ACTIVE",
  },

  // ── High Risk Tools (approval-only, AI never executes directly) ──
  ...([
    ["high_risk.finance.refund", "Refund", "Process payment refund", "finance.service.refund"],
    // Wallet adjustment already has its OWN maker-checker chain in
    // financialAdjustmentService (create → approve → execute). A future handler must call
    // `execute` and must not bypass that chain — the AI approval is a second gate, not a
    // replacement for it.
    ["high_risk.finance.walletAdjustment", "Wallet Adjustment", "Adjust customer wallet balance", "financialAdjustment.service.execute"],
    ["high_risk.finance.settlement", "Settlement", "Trigger settlement run", "settlementSync.service.runSync"],
    ["high_risk.finance.payout", "Payout", "Process partner payout", "settlement.service.payout"],
    ["high_risk.finance.ledgerEntry", "Ledger Entry", "Manual ledger entry", "finance.service.ledger"],
    ["high_risk.finance.financeApproval", "Finance Approval", "Approve financial adjustment", "finance.service.approve"],
    ["high_risk.compliance.accountFreeze", "Account Freeze", "Freeze user account", "financialRisk.service.applyHold"],
    // No such service exists. `admin.service` offers banUser and verifyProvider, but nothing
    // that suspends a provider. Registered but DISABLED so the capability stays visible and
    // governed while being honest that it cannot run — rather than advertising a mapping a
    // handler author would follow into a dead end.
    //
    // DISABLED, not "INACTIVE": `AiToolStatus` is ACTIVE | DEPRECATED | DISABLED, and "INACTIVE"
    // was never one of them. Prisma rejected it at boot with `Invalid value for argument
    // 'status'`, which killed the whole backend before it could listen — this is the only entry in
    // the catalog that sets a status, so nothing else masked it. DEPRECATED would have been the
    // wrong word anyway: this tool was never available to phase out.
    ["high_risk.compliance.partnerSuspend", "Partner Suspend", "Suspend partner account", "admin.service.suspendProvider", "DISABLED"],
    ["high_risk.compliance.customerBan", "Customer Ban", "Ban customer account", "admin.service.banUser"],
    ["high_risk.security.roleEscalation", "Role Escalation", "Escalate user role privileges", "rbac.service.escalate"],
    ["high_risk.platform.featureFlagChange", "Feature Flag Change", "Modify feature flag", "featureFlag.service.update"],
    ["high_risk.platform.secrets", "Secrets", "Access or rotate secrets", "secrets.service.rotate"],
    ["high_risk.platform.configuration", "Configuration", "Modify platform configuration", "financeConfig.service.update"],
    ["high_risk.platform.infrastructure", "Infrastructure", "Infrastructure change", "ops.service.infrastructure"],
  ] as const).map(([toolId, name, description, serviceMapping, status]) => ({
    toolId,
    name,
    description,
    category: "HIGH_RISK" as const,
    version: "1.0.0",
    requiredPermission: `tools.high_risk.${toolId.split(".")[2]}`,
    requiredRole: "ADMIN",
    requiredPolicy: "admin.high_risk.approval",
    riskLevel: "CRITICAL" as const,
    parameters: [{ name: "payload", type: "object" as const, required: true, description: "Action payload (validated by approver)" }],
    validationSchema: { type: "object", required: ["payload"] },
    timeoutMs: 60_000,
    maxRetries: 0,
    auditRequired: true,
    approvalRequired: true,
    serviceMapping,
    eventMapping: "homigo.ai.tool.high_risk",
    metricsKey: toolId.split(".").pop(),
    costEstimateUsd: 0.01,
    owner: "platform-security",
    status: (status ?? "ACTIVE") as AiToolStatus,
  })),

  // ── Phase 16: governed agent read surface ──
  //
  // Kept in their own module because they belong to the agent layer, and spread in here so
  // there is exactly ONE catalog. A separate registry would mean a separate set of policy,
  // audit and discovery guarantees to keep in step.
  ...PHASE16_AGENT_TOOLS,
];

export const TOOL_CATEGORIES = ["READ", "WRITE", "HIGH_RISK"] as const;

export function countToolsByCategory(): Record<string, number> {
  const counts: Record<string, number> = { READ: 0, WRITE: 0, HIGH_RISK: 0 };
  for (const tool of TOOL_CATALOG) {
    counts[tool.category] = (counts[tool.category] ?? 0) + 1;
  }
  return counts;
}
