-- Money drift validation: count rows where paise != ROUND(float*100).
-- Expected: every count = 0.
SELECT 'bookings.final_amount' AS col, COUNT(*) AS mismatches FROM bookings WHERE final_amount_paise IS DISTINCT FROM money_to_paise(final_amount)
UNION ALL SELECT 'bookings.total_amount', COUNT(*) FROM bookings WHERE total_amount_paise IS DISTINCT FROM money_to_paise(total_amount)
UNION ALL SELECT 'bookings.refund_amount', COUNT(*) FROM bookings WHERE refund_amount_paise IS DISTINCT FROM money_to_paise(refund_amount)
UNION ALL SELECT 'payments.amount', COUNT(*) FROM payments WHERE amount_paise IS DISTINCT FROM money_to_paise(amount)
UNION ALL SELECT 'payments.amount_paid', COUNT(*) FROM payments WHERE amount_paid_paise IS DISTINCT FROM money_to_paise(amount_paid)
UNION ALL SELECT 'payments.refunded_amount', COUNT(*) FROM payments WHERE refunded_amount_paise IS DISTINCT FROM money_to_paise(refunded_amount)
UNION ALL SELECT 'wallet_transactions.amount', COUNT(*) FROM wallet_transactions WHERE amount_paise IS DISTINCT FROM money_to_paise(amount)
UNION ALL SELECT 'wallet_transactions.balance_after', COUNT(*) FROM wallet_transactions WHERE wallet_balance_after_paise IS DISTINCT FROM money_to_paise(wallet_balance_after)
UNION ALL SELECT 'earnings.gross_amount', COUNT(*) FROM earnings WHERE gross_amount_paise IS DISTINCT FROM money_to_paise(gross_amount)
UNION ALL SELECT 'earnings.net_earning', COUNT(*) FROM earnings WHERE net_earning_paise IS DISTINCT FROM money_to_paise(net_earning)
UNION ALL SELECT 'withdrawals.amount', COUNT(*) FROM withdrawals WHERE amount_paise IS DISTINCT FROM money_to_paise(amount)
UNION ALL SELECT 'withdrawals.net_amount', COUNT(*) FROM withdrawals WHERE net_amount_paise IS DISTINCT FROM money_to_paise(net_amount)
UNION ALL SELECT 'ledger_entries.debit', COUNT(*) FROM ledger_entries WHERE debit_paise IS DISTINCT FROM money_to_paise(debit)
UNION ALL SELECT 'ledger_entries.credit', COUNT(*) FROM ledger_entries WHERE credit_paise IS DISTINCT FROM money_to_paise(credit)
UNION ALL SELECT 'wallet_transfers.amount', COUNT(*) FROM wallet_transfers WHERE amount_paise IS DISTINCT FROM money_to_paise(amount)
UNION ALL SELECT 'membership_cashbacks.amount', COUNT(*) FROM membership_cashbacks WHERE amount_paise IS DISTINCT FROM money_to_paise(amount)
UNION ALL SELECT 'users.wallet_balance', COUNT(*) FROM users WHERE wallet_balance_paise IS DISTINCT FROM money_to_paise(wallet_balance)
UNION ALL SELECT 'providers.wallet_balance', COUNT(*) FROM providers WHERE wallet_balance_paise IS DISTINCT FROM money_to_paise(wallet_balance)
UNION ALL SELECT 'providers.reserved_balance', COUNT(*) FROM providers WHERE reserved_balance_paise IS DISTINCT FROM money_to_paise(reserved_balance)
UNION ALL SELECT 'refund_requests.amount', COUNT(*) FROM refund_requests WHERE amount_paise IS DISTINCT FROM money_to_paise(amount)
UNION ALL SELECT 'chargebacks.amount', COUNT(*) FROM chargebacks WHERE amount_paise IS DISTINCT FROM money_to_paise(amount)
ORDER BY 1;
