/**
 * Render the Phase 06 requirement proposal as the owner-review document (markdown on stdout).
 * Generated from scripts/data/phase-06-requirement-proposal.ts, so the review text and what
 * apply-requirement-proposal.ts writes can never drift apart.
 *
 *   bun run scripts/render-requirement-proposal.ts > docs/service-domain/phase-06-requirement-content-proposal.md
 */
import { requirementAssignmentSchema, customerRequirementsView, resolveServiceRequirements, type RequirementItemInfo } from "../src/lib/service-requirements";
import { CATALOGUE, OWNER_DECISIONS, PROPOSAL, PROPOSAL_VERSION } from "./data/phase-06-requirement-proposal";

const items: Record<string, RequirementItemInfo> = Object.fromEntries(CATALOGUE.map((i) => [i.code, { code: i.code, kind: i.kind, name: i.name, customerLabel: i.customerLabel ?? null, description: i.description ?? null, isActive: true }]));
const KIND = { MATERIAL: "Material", EQUIPMENT: "Equipment", CUSTOMER_PRECONDITION: "Precondition" } as const;
const ENF = { INFORMATIONAL: "info", WARNING: "please", REQUIRED_BEFORE_ARRIVAL: "checked on arrival", REQUIRED_AT_START: "checked at start", REQUIRED_BEFORE_BOOKING: "**must confirm to book**" } as const;
const CHARGE = { INCLUDED: "included", CHARGEABLE: "chargeable", SEPARATE_QUOTE: "**separate quote**", NOT_APPLICABLE: "—" } as const;
const out: string[] = [];
out.push(`# Phase 06 — requirement content proposal ${PROPOSAL_VERSION} (OWNER REVIEW)`);
out.push("");
out.push("Generated by `scripts/render-requirement-proposal.ts` from `scripts/data/phase-06-requirement-proposal.ts`. Do not edit by hand — edit the data file and re-render.");
out.push("");
out.push("**Status:** drafted, rehearsed on a restored copy of the live catalogue, **not applied to `homigo_db`**. Every assignment carries an internal provenance note (`PROPOSAL …`) that customers and partners never see. Quantities, product specs, safety data and suppliers are not proposed anywhere.");
out.push("");
out.push("## How to read a line");
out.push("");
out.push("`kind · who provides · charge · enforcement` — then the customer sentence. Enforcement: *info* is shown only; *please* is shown as preparation advice; *checked on arrival / at start* the professional verifies; **must confirm to book** blocks the booking until the customer ticks it.");
out.push("");
out.push("## Decisions needed from the owner");
out.push("");
out.push("| Service | Decision |");
out.push("|---|---|");
for (const d of OWNER_DECISIONS) out.push(`| ${d.service} | ${d.decision} |`);
out.push("");
out.push("## Shared catalogue");
out.push("");
for (const kind of ["MATERIAL", "EQUIPMENT", "CUSTOMER_PRECONDITION"] as const) {
  out.push(`**${KIND[kind]}s (${CATALOGUE.filter((i) => i.kind === kind).length})**: ` + CATALOGUE.filter((i) => i.kind === kind).map((i) => `${i.name} (\`${i.code}\`)`).join(" · "));
  out.push("");
}
out.push("## Per service");
out.push("");
for (const slug of Object.keys(PROPOSAL).sort()) {
  const parsed = PROPOSAL[slug]!.map((a) => requirementAssignmentSchema.parse(a));
  const res = resolveServiceRequirements({ requirements: parsed, requirementItems: items, variants: [], addons: [] } as never, { variantId: null, addonIds: [], quantity: 1 });
  out.push(`### ${slug}`);
  out.push("");
  out.push("| # | kind · provider · charge · enforcement | item | what the customer reads |");
  out.push("|---|---|---|---|");
  parsed.forEach((a, i) => {
    const it = items[a.itemCode]!;
    const who = a.responsibility === "PROFESSIONAL" ? "we bring" : a.responsibility === "CUSTOMER" ? (it.kind === "CUSTOMER_PRECONDITION" ? "customer" : "customer provides") : a.responsibility.toLowerCase();
    const text = [a.customerNote, a.customerWarning ? `⚠ ${a.customerWarning}` : null].filter(Boolean).join(" ");
    out.push(`| ${i + 1} | ${KIND[it.kind]} · ${who} · ${CHARGE[a.charge]} · ${ENF[a.enforcement]}${a.optional ? " · optional" : ""} | ${it.customerLabel ?? it.name} | ${text || "—"} |`);
  });
  if (res.ok) {
    const v = customerRequirementsView(res.items);
    const line = (k: keyof typeof v, label: string) => (Array.isArray(v[k]) && v[k].length ? `${label}: ${(v[k] as { label: string }[]).map((x) => x.label).join(", ")}` : null);
    out.push("");
    out.push("Customer sees → " + [line("beforeBooking", "**Confirm to book**"), line("beforeArrival", "Have ready"), line("youProvide", "You provide"), line("weBring", "We bring"), line("optional", "Optional")].filter(Boolean).join(" · "));
  }
  out.push("");
}
out.push("## Applying it");
out.push("");
out.push("```");
out.push("bun --env-file=.env run scripts/apply-requirement-proposal.ts --target live --dry-run");
out.push("bun --env-file=.env run scripts/apply-requirement-proposal.ts --target live --actor-id <super admin user id> --evidence docs/operations/evidence/phase-06-proposal-homigo_db-<date>.json");
out.push("```");
out.push("");
out.push("Per service: `--services a,b`. Idempotent; a service the owner has already edited in admin tab 09b is refused unless `--overwrite`. After applying, edit any line in the admin panel — the provenance note tells a proposal from a decision.");
console.log(out.join("\n"));
