import {
  Briefcase,
  Car,
  HeartHandshake,
  Home,
  PartyPopper,
  PawPrint,
  Refrigerator,
  Rocket,
  Scissors,
  Shirt,
  ShieldCheck,
  Sparkles,
  Wrench,
} from "lucide-react";
import type {
  Audience,
  BeautyType,
  CategoryDef,
  CategoryId,
  CrossListing,
  ServiceDef,
} from "@/lib/catalog/types";

/* ------------------------------------------------------------------ */
/* Categories — display order is the order of this array.             */
/* ------------------------------------------------------------------ */

const CLEANING_PREP = [
  "Clear personal, fragile and valuable items from the area.",
  "Make sure water and electricity are available.",
  "Keep the area accessible when your professional arrives.",
];

const REPAIR_PREP = [
  "Describe the issue in booking instructions — photos help.",
  "Keep the affected area clear and accessible.",
  "Switch off the appliance or supply if it is safe to do so.",
];

export const CATEGORIES: CategoryDef[] = [
  {
    id: "home-help",
    name: "Home Help",
    shortName: "Home Help",
    tagline: "Everyday help, by the hour or by the task.",
    description:
      "A trained helper for the daily work of running a home — from dusting and utensils to laundry and kitchen prep.",
    icon: Home,
    tone: "#059669",
    treatment: "default",
    subgroups: [
      { id: "hourly", name: "Hourly help" },
      { id: "daily", name: "Daily chores" },
      { id: "clothes", name: "Clothes care" },
      { id: "organise", name: "Organise & move" },
    ],
    prepare: CLEANING_PREP,
  },
  {
    id: "home-cleaning",
    name: "Home Cleaning",
    shortName: "Cleaning",
    tagline: "Professional cleaning for every corner of your home.",
    description:
      "Room-by-room and whole-home cleaning, plus deep care for sofas, mattresses, carpets and fixtures.",
    icon: Sparkles,
    tone: "#0d9488",
    treatment: "default",
    backendCategories: ["cleaning"],
    subgroups: [
      { id: "rooms", name: "Rooms & whole home" },
      { id: "furnishings", name: "Furnishings" },
      { id: "fixtures", name: "Fixtures & appliances" },
    ],
    prepare: CLEANING_PREP,
  },
  {
    id: "event-occasion",
    name: "Event & Occasion",
    shortName: "Events",
    tagline: "Ready before the guests. Reset after they leave.",
    description:
      "Fast, focused cleaning and help around parties, festivals and big days at home.",
    icon: PartyPopper,
    tone: "#db2777",
    treatment: "default",
    prepare: CLEANING_PREP,
  },
  {
    id: "home-maintenance",
    name: "Home Maintenance",
    shortName: "Maintenance",
    tagline: "Repairs and installs, done properly.",
    description:
      "Plumbing, electrical, painting, carpentry and handyman work for a home that simply works.",
    icon: Wrench,
    tone: "#d97706",
    treatment: "default",
    backendCategories: ["repair", "home"],
    subgroups: [
      { id: "repairs", name: "Repairs" },
      { id: "installs", name: "Installation & assembly" },
      { id: "painting", name: "Painting" },
    ],
    prepare: REPAIR_PREP,
  },
  {
    id: "appliance-care",
    name: "Appliance & Utility Care",
    shortName: "Appliances",
    tagline: "Keep your appliances running like new.",
    description:
      "Servicing, cleaning and installation for ACs, kitchen appliances, geysers and washing machines.",
    icon: Refrigerator,
    tone: "#0284c7",
    treatment: "default",
    subgroups: [
      { id: "cooling", name: "Air conditioning" },
      { id: "kitchen", name: "Kitchen appliances" },
      { id: "utility", name: "Utility & install" },
    ],
    prepare: REPAIR_PREP,
  },
  {
    id: "specialized-care",
    name: "Specialized Care",
    shortName: "Specialized",
    tagline: "Specialist treatments for the jobs that need them.",
    description:
      "Pest control, sanitisation, water tanks, facades and specialist surfaces — handled with the right methods.",
    icon: ShieldCheck,
    tone: "#4f46e5",
    treatment: "default",
    backendCategories: ["apartments"],
    prepare: CLEANING_PREP,
  },
  {
    id: "laundry-fabric",
    name: "Laundry & Fabric Care",
    shortName: "Laundry",
    tagline: "Fresh, pressed and neatly folded.",
    description: "Washing, ironing, folding and care for curtains, fabrics and upholstery.",
    icon: Shirt,
    tone: "#7c3aed",
    treatment: "default",
  },
  {
    id: "vehicle-care",
    name: "Vehicle Care",
    shortName: "Vehicle",
    tagline: "Doorstep care for your car and bike.",
    description: "Exterior, interior and detailing services for cars and bikes, where they are parked.",
    icon: Car,
    tone: "#475569",
    treatment: "default",
    prepare: [
      "Park where there is room to work around the vehicle.",
      "Remove valuables from the vehicle before the visit.",
      "Let us know if water access is limited at your parking spot.",
    ],
  },
  {
    id: "beauty",
    name: "Beauty & Grooming",
    shortName: "Beauty",
    tagline: "Personal care, delivered to your doorstep.",
    description:
      "Hair, skin, nails, makeup and grooming for women, men, kids and seniors — in the comfort of home.",
    icon: Scissors,
    tone: "#e11d48",
    treatment: "beauty",
    backendCategories: ["beauty"],
    planned: [
      "Choose who the service is for",
      "Pick a service variant and duration",
      "Add-ons for each service",
      "Choose a time slot that suits you",
    ],
    prepare: [
      "Keep a well-lit space with a chair and a nearby power point.",
      "Mention allergies or skin sensitivities in booking instructions.",
    ],
  },
  {
    id: "senior-care",
    name: "Senior Care",
    shortName: "Senior Care",
    tagline: "Dependable, respectful support for the people who matter most.",
    description:
      "Everyday assistance and companionship for seniors — errands, appointments and time together.",
    icon: HeartHandshake,
    tone: "#b45309",
    treatment: "senior",
    notice:
      "Senior Care is non-medical assistance and companionship. It does not include nursing, medical care or administering medication.",
    planned: [
      "A care profile with routines and preferences",
      "Visit duration that fits the day",
      "Family contact for updates",
      "Recurring visits",
    ],
  },
  {
    id: "pet-care",
    name: "Pet Care",
    shortName: "Pet Care",
    tagline: "Care for your pets while you are busy or away.",
    description: "Walking, feeding, sitting and basic grooming from people who love animals.",
    icon: PawPrint,
    tone: "#ea580c",
    treatment: "pet",
    notice: "Pet Care is non-veterinary. For medical concerns, please consult a veterinarian.",
    planned: [
      "A pet profile with type, size and temperament",
      "Visit duration and preferred time",
      "Feeding and care instructions",
      "Recurring visits",
    ],
  },
  {
    id: "executive-concierge",
    name: "Executive & Concierge",
    shortName: "Concierge",
    tagline: "Everyday assistance for your personal and professional life.",
    description: "Drivers, assistants, errands and concierge help — booked by the hour or by the task.",
    icon: Briefcase,
    tone: "#1e293b",
    treatment: "executive",
    planned: [
      "Hourly or fixed-task booking",
      "Pickup and drop details",
      "Task checklist for your assistant",
      "Recurring bookings",
    ],
  },
  {
    id: "special-services",
    name: "Special & Future Services",
    shortName: "Special",
    tagline: "Bigger moments, handled end to end.",
    description: "Moves, setups, rental turnovers and property visits — and anything else you need.",
    icon: Rocket,
    tone: "#0f766e",
    treatment: "future",
    planned: ["Scope agreed with you before the visit", "Custom quote", "Flexible scheduling"],
  },
];

export const CATEGORY_BY_ID = new Map(CATEGORIES.map((c) => [c.id, c]));

/* ------------------------------------------------------------------ */
/* Services                                                            */
/* ------------------------------------------------------------------ */

const S = (def: ServiceDef): ServiceDef => def;

const ALL_AUDIENCES: Audience[] = ["women", "men", "girls", "boys", "senior-women", "senior-men"];

const REPAIR_EXCLUDES = [
  "Spare parts and materials",
  "Civil work such as wall breaking, tiling or masonry",
];

const SERVICES_CORE: ServiceDef[] = [
  /* ---------------- 01 Home Help ---------------- */
  S({
    slug: "hourly-home-help",
    name: "Hourly Home Help",
    category: "home-help",
    subgroup: "hourly",
    bind: ["hourly-bookings"],
    short: "Book a trained professional by the hour for everyday household tasks.",
    pricingModel: "hourly",
    hourly: true,
    image: "/homigo-welcome.png",
    aliases: ["hourly", "maid", "helper", "house help", "part time", "by the hour", "domestic help"],
    includes: [
      "Dusting, wiping, sweeping and mopping",
      "Utensils, laundry and folding",
      "Kitchen prep and tidying up",
      "Any household task you set, within the booked time",
    ],
    excludes: [
      "Work that needs specialised tools or chemicals",
      "Electrical, plumbing or repair work",
      "Personal, nursing or medical care",
    ],
    addons: true,
  }),
  S({
    slug: "dusting-wiping",
    name: "Dusting & Wiping",
    category: "home-help",
    subgroup: "daily",
    bind: ["dusting-wiping"],
    short: "Dust-free surfaces, shelves and furniture across your home.",
    pricingModel: "fixed",
    aliases: ["dusting", "wiping", "dust", "cobweb"],
    includes: [
      "Dusting of furniture, shelves and reachable surfaces",
      "Wiping of tables, switchboards and door handles",
      "Cobweb removal from reachable corners",
    ],
    excludes: ["Floor mopping (see Sweeping & Mopping)", "High-reach areas that need a ladder"],
    addons: true,
  }),
  S({
    slug: "sweeping-mopping",
    name: "Sweeping & Mopping",
    category: "home-help",
    subgroup: "daily",
    bind: ["sweeping-mopping"],
    short: "Swept, mopped and fresh floors in every room.",
    pricingModel: "fixed",
    aliases: ["sweeping", "mopping", "floor", "jhadu pocha", "mop"],
    includes: ["Sweeping of all accessible floors", "Disinfectant mopping of every room"],
    excludes: ["Machine scrubbing or floor polishing", "Moving heavy furniture"],
    addons: true,
  }),
  S({
    slug: "utensils",
    name: "Utensils",
    category: "home-help",
    subgroup: "daily",
    bind: ["utensil-washing"],
    short: "Utensils washed, dried and stacked back on the shelf.",
    pricingModel: "fixed",
    aliases: ["utensil", "dishes", "dish washing", "bartan", "washing up"],
    includes: ["Washing of everyday utensils", "Drying and stacking on the shelf or rack"],
    excludes: ["Restoring burnt or heavily stained cookware", "Kitchen surface cleaning"],
    addons: true,
  }),
  S({
    slug: "kitchen-prep",
    name: "Kitchen Prep",
    category: "home-help",
    subgroup: "daily",
    bind: ["kitchen-prep"],
    short: "Chopping, marination and meal prep, ready when you are.",
    pricingModel: "fixed",
    aliases: ["chopping", "cutting", "meal prep", "cook", "vegetables"],
    includes: ["Washing and chopping vegetables", "Marination and meal prep as you instruct"],
    excludes: ["Cooking full meals", "Grocery shopping"],
  }),
  S({
    slug: "ironing-folding",
    name: "Ironing & Folding",
    category: "laundry-fabric",
    bind: ["ironing-folding"],
    short: "Crisp ironing and neat folding for everyday clothes.",
    pricingModel: "fixed",
    aliases: ["ironing", "folding", "press", "iron", "istri"],
    includes: ["Ironing of everyday garments", "Neat folding and stacking"],
    excludes: ["Dry-clean-only garments", "Repairs or alterations"],
  }),
  S({
    slug: "packing-unpacking",
    name: "Packing & Unpacking",
    category: "home-help",
    subgroup: "organise",
    bind: ["packing-unpacking"],
    short: "Careful packing or unpacking — boxes, labelling and arranging.",
    pricingModel: "fixed",
    aliases: ["packing", "unpacking", "moving", "shifting", "relocation", "boxes"],
    includes: ["Packing or unpacking of household items", "Labelling boxes and arranging items"],
    excludes: ["Transport or loading into vehicles", "Dismantling large furniture"],
  }),
  S({
    slug: "home-organization",
    name: "Home Organization",
    category: "home-help",
    subgroup: "organise",
    short: "Wardrobes, shelves and storage arranged into a system that lasts.",
    pricingModel: "hourly",
    aliases: ["organise", "organize", "organizing", "storage", "arranging"],
  }),
  S({
    slug: "decluttering-assistance",
    name: "Decluttering Assistance",
    category: "home-help",
    subgroup: "organise",
    short: "Help sorting what to keep, donate or let go of — room by room.",
    pricingModel: "hourly",
    aliases: ["declutter", "decluttering", "clearing", "sorting"],
  }),

  /* ---------------- 02 Home Cleaning ---------------- */
  S({
    slug: "bathroom-cleaning",
    name: "Bathroom Cleaning",
    category: "home-cleaning",
    subgroup: "rooms",
    bind: ["bathroom-cleaning"],
    short: "Professional bathroom cleaning at your doorstep.",
    pricingModel: "fixed",
    aliases: ["bathroom", "toilet", "washroom", "restroom", "descaling"],
    includes: [
      "Toilet, washbasin and taps",
      "Wall tiles and floor scrubbing",
      "Mirrors and glass surfaces",
      "Shower area and fittings",
    ],
    excludes: [
      "Repair or replacement of fittings",
      "Removal of permanent stains or surface damage",
      "Clearing blocked drains",
    ],
    addons: true,
  }),
  S({
    slug: "kitchen-cleaning",
    name: "Kitchen Cleaning",
    category: "home-cleaning",
    subgroup: "rooms",
    bind: ["kitchen-cleaning"],
    short: "A degreased, spotless kitchen — counters, sink and surfaces.",
    pricingModel: "fixed",
    aliases: ["kitchen", "degrease", "counter", "slab"],
    includes: [
      "Countertops, backsplash and sink",
      "Exterior of cabinets and appliances",
      "Chimney exterior",
      "Floor cleaning",
    ],
    excludes: [
      "Inside of appliances (add fridge or microwave cleaning)",
      "Inside of cabinets (see Kitchen Cabinet Cleaning)",
      "Utensil washing",
    ],
    addons: true,
  }),
  S({
    slug: "deep-home-cleaning",
    name: "Deep Home Cleaning",
    category: "home-cleaning",
    subgroup: "rooms",
    bind: ["deep-cleaning"],
    short: "Top-to-bottom deep cleaning for your entire home.",
    pricingModel: "fixed",
    aliases: ["deep clean", "deep cleaning", "full home", "whole house", "complete cleaning"],
    includes: [
      "Rooms, kitchen and bathrooms",
      "Dusting of reachable surfaces and fixtures",
      "Floor scrubbing and mopping",
      "Doors, windows and switchboards",
    ],
    excludes: [
      "Inside of appliances (available as add-ons)",
      "Wall painting or repairs",
      "Moving heavy furniture",
    ],
    addons: true,
  }),
  S({
    slug: "wardrobe-cleaning",
    name: "Complete Wardrobe Cleaning",
    category: "home-cleaning",
    subgroup: "furnishings",
    bind: ["wardrobe-cleaning"],
    short: "Wardrobe emptied, cleaned, decluttered and re-organised.",
    pricingModel: "fixed",
    aliases: ["wardrobe", "closet", "almirah", "cupboard"],
    includes: ["Emptying and cleaning shelves and drawers", "Re-organising clothes and items"],
    excludes: ["Washing or ironing clothes", "Carpentry or hinge repairs"],
  }),
  S({
    slug: "kitchen-cabinet-cleaning",
    name: "Kitchen Cabinet Cleaning",
    category: "home-cleaning",
    subgroup: "fixtures",
    bind: ["kitchen-cabinet-cleaning"],
    short: "Cabinets and drawers emptied, degreased and re-lined.",
    pricingModel: "fixed",
    aliases: ["cabinet", "drawers", "kitchen cupboard", "modular kitchen"],
    includes: ["Emptying cabinets and drawers", "Inside and outside degreasing", "Re-arranging items"],
    excludes: ["Hinge or channel repairs", "Replacing shelf liners"],
    addons: true,
  }),
  S({
    slug: "window-cleaning",
    name: "Window Cleaning",
    category: "home-cleaning",
    subgroup: "rooms",
    bind: ["window-cleaning"],
    short: "Streak-free glass, tracks and grills for every window.",
    pricingModel: "fixed",
    aliases: ["window", "windows", "glass", "grill", "sliding"],
    includes: ["Inside glass cleaning", "Window tracks and frames", "Grills within safe reach"],
    excludes: ["Exterior glass on high floors without safe access", "Repairs to frames or mesh"],
    addons: true,
  }),
  S({
    slug: "balcony-cleaning",
    name: "Balcony Cleaning",
    category: "home-cleaning",
    subgroup: "rooms",
    bind: ["balcony-cleaning"],
    short: "Balcony floor, railing and glass — clean and inviting.",
    pricingModel: "fixed",
    aliases: ["balcony", "terrace", "railing", "sit out"],
    includes: ["Floor scrubbing and mopping", "Railing and glass panel cleaning"],
    excludes: ["Facade or exterior wall cleaning", "Plant repotting (see Plant Care)"],
    addons: true,
  }),
  S({
    slug: "fan-cleaning",
    name: "Fan Cleaning",
    category: "home-cleaning",
    subgroup: "fixtures",
    bind: ["fan-cleaning"],
    short: "Ceiling and wall fan blades degreased, without the dust shower.",
    pricingModel: "fixed",
    aliases: ["fan", "ceiling fan", "exhaust fan", "blades"],
    includes: ["Blade and canopy cleaning", "Degreasing of kitchen or exhaust fans on request"],
    excludes: ["Electrical repairs or fan installation"],
    addons: true,
  }),
  S({
    slug: "fridge-cleaning",
    name: "Fridge Cleaning",
    category: "home-cleaning",
    subgroup: "fixtures",
    bind: ["fridge-cleaning"],
    short: "Inside-out fridge degrease, defrost wipe-down and shelf sanitisation.",
    pricingModel: "fixed",
    aliases: ["fridge", "refrigerator", "freezer", "defrost"],
    includes: ["Shelves, trays and drawers", "Interior and door seals", "Exterior wipe-down"],
    excludes: ["Gas refill or repairs", "Disposing of food items"],
    prepare: ["Empty the fridge and switch it off a few hours before the visit if possible."],
    addons: true,
    excludeAddons: ["fridge"],
  }),
  S({
    slug: "sofa-deep-cleaning",
    name: "Sofa Deep Cleaning",
    category: "home-cleaning",
    subgroup: "furnishings",
    bind: ["sofa-deep-cleaning"],
    short: "Shampoo, vacuum and sanitise sofas and upholstery.",
    pricingModel: "fixed",
    aliases: ["sofa", "couch", "upholstery", "shampoo", "recliner"],
    includes: ["Vacuuming of seats, backs and cushions", "Shampoo and stain treatment", "Sanitisation"],
    excludes: ["Leather restoration or re-upholstery", "Guaranteed removal of old or set-in stains"],
    prepare: ["Plan to keep the sofa unused for a few hours afterwards while it dries."],
    addons: true,
    excludeAddons: ["sofa"],
  }),
  S({
    slug: "mattress-sanitization",
    name: "Mattress Sanitization",
    category: "home-cleaning",
    subgroup: "furnishings",
    bind: ["mattress-sanitization"],
    short: "Deep vacuum and treatment for a fresher, cleaner sleep.",
    pricingModel: "fixed",
    aliases: ["mattress", "bed", "dust mite", "sanitisation"],
    includes: ["Deep vacuuming of both sides", "Sanitising treatment"],
    excludes: ["Bed frame repairs", "Washing of bed linen"],
    addons: true,
  }),
  S({
    slug: "carpet-shampooing",
    name: "Carpet Shampooing",
    category: "home-cleaning",
    subgroup: "furnishings",
    bind: ["carpet-shampooing"],
    short: "Machine shampoo and stain treatment for carpets and rugs.",
    pricingModel: "fixed",
    aliases: ["carpet", "rug", "dhurrie", "mat"],
    includes: ["Vacuuming", "Machine shampoo", "Spot stain treatment"],
    excludes: ["Silk or antique carpet care", "Guaranteed removal of set-in stains"],
    addons: true,
  }),
  S({
    slug: "floor-cleaning",
    name: "Floor Cleaning",
    category: "home-cleaning",
    subgroup: "rooms",
    short: "Machine scrubbing for tiles, marble and stone floors.",
    pricingModel: "area",
    unit: "sq. ft.",
    aliases: ["floor scrubbing", "marble", "tiles", "floor polish"],
  }),
  S({
    slug: "glass-surface-cleaning",
    name: "Glass & Surface Cleaning",
    category: "home-cleaning",
    subgroup: "rooms",
    short: "Mirrors, glass partitions and shiny surfaces without streaks.",
    pricingModel: "fixed",
    aliases: ["glass", "mirror", "partition", "surface"],
  }),
  S({
    slug: "move-in-move-out-cleaning",
    name: "Move-In / Move-Out Cleaning",
    category: "home-cleaning",
    subgroup: "rooms",
    short: "An empty home cleaned end to end before you move in or hand it over.",
    pricingModel: "package",
    aliases: ["move in", "move out", "vacate", "shifting clean", "handover", "empty flat"],
  }),

  /* ---------------- 03 Event & Occasion ---------------- */
  S({
    slug: "pre-party-express-clean",
    name: "Pre-Party Express Clean",
    category: "event-occasion",
    bind: ["pre-party-express-clean"],
    short: "A rapid whole-home refresh before your guests arrive.",
    pricingModel: "fixed",
    aliases: ["party", "guests", "pre party", "before party", "express"],
    includes: ["Quick dusting and surface wipe-down", "Floors swept and mopped", "Bathrooms refreshed"],
    excludes: ["Deep cleaning of kitchens or appliances", "Decoration setup"],
    addons: true,
  }),
  S({
    slug: "after-party-express-clean",
    name: "After-Party Express Clean",
    category: "event-occasion",
    bind: ["after-party-express-clean"],
    short: "Fast post-event cleanup — trash, dishes, floors and more.",
    pricingModel: "fixed",
    aliases: ["after party", "post party", "cleanup", "express"],
    includes: ["Trash collection and bagging", "Dishes and glassware", "Floors swept and mopped"],
    excludes: ["Carpet or sofa stain treatment (book separately)", "Waste disposal outside the premises"],
    addons: true,
  }),
  S({
    slug: "festival-home-preparation",
    name: "Festival Home Preparation",
    category: "event-occasion",
    short: "Get your home festival-ready — Diwali, Holi, Eid, Christmas and more.",
    pricingModel: "package",
    aliases: ["festival", "diwali", "holi", "eid", "christmas", "pooja", "puja"],
  }),
  S({
    slug: "post-event-cleanup",
    name: "Post-Event Cleanup",
    category: "event-occasion",
    short: "Larger gatherings and functions, cleaned up after the last guest leaves.",
    pricingModel: "quote",
    aliases: ["event", "function", "gathering", "cleanup"],
  }),

  /* ---------------- 04 Home Maintenance ---------------- */
  S({
    slug: "plumbing-repair",
    name: "Plumbing Repair",
    category: "home-maintenance",
    subgroup: "repairs",
    bind: ["plumbing"],
    short: "Leak fixes, tap installation and drainage issues.",
    pricingModel: "fixed",
    aliases: ["plumber", "plumbing", "leak", "tap", "pipe", "drain", "flush", "blockage"],
    includes: ["Inspection of the reported issue", "Repair work agreed with you during the visit"],
    excludes: REPAIR_EXCLUDES,
  }),
  S({
    slug: "electrician",
    name: "Electrician",
    category: "home-maintenance",
    subgroup: "repairs",
    bind: ["electrician"],
    short: "Wiring, switches, fans and appliance installation.",
    pricingModel: "fixed",
    aliases: ["electric", "electrical", "wiring", "switch", "socket", "mcb", "light", "fan installation"],
    includes: ["Inspection of the reported issue", "Repair or installation work agreed during the visit"],
    excludes: ["Wires, switches and other materials", "Concealed rewiring that needs wall chasing"],
  }),
  S({
    slug: "home-painting",
    name: "Home Painting",
    category: "home-maintenance",
    subgroup: "painting",
    bind: ["home-painting"],
    short: "Interior and exterior wall painting.",
    pricingModel: "fixed",
    aliases: ["paint", "painting", "painter", "wall", "colour", "color"],
    includes: ["Painting of the walls and areas agreed with you"],
    excludes: ["Waterproofing or seepage treatment", "Structural wall repairs"],
    prepare: ["Move furniture away from the walls to be painted where possible."],
  }),
  S({
    slug: "minor-carpentry",
    name: "Minor Carpentry",
    category: "home-maintenance",
    subgroup: "repairs",
    short: "Hinges, handles, locks and small woodwork repairs.",
    pricingModel: "inspection",
    aliases: ["carpenter", "carpentry", "hinge", "door", "lock", "wood"],
  }),
  S({
    slug: "furniture-assembly",
    name: "Furniture Assembly",
    category: "home-maintenance",
    subgroup: "installs",
    short: "Flat-pack beds, wardrobes, tables and shelves assembled right.",
    pricingModel: "per-unit",
    unit: "item",
    aliases: ["assembly", "assemble", "flat pack", "ikea", "bed assembly"],
  }),
  S({
    slug: "wall-mounting",
    name: "Wall Mounting",
    category: "home-maintenance",
    subgroup: "installs",
    short: "TVs, shelves, mirrors and frames mounted securely.",
    pricingModel: "per-unit",
    unit: "item",
    aliases: ["tv mount", "tv installation", "shelf", "mirror", "drill"],
  }),
  S({
    slug: "curtain-rod-installation",
    name: "Curtain / Rod Installation",
    category: "home-maintenance",
    subgroup: "installs",
    short: "Curtain rods, tracks and blinds fitted level and firm.",
    pricingModel: "per-unit",
    unit: "window",
    aliases: ["curtain", "rod", "blinds", "track"],
  }),
  S({
    slug: "general-handyman",
    name: "General Handyman",
    category: "home-maintenance",
    subgroup: "repairs",
    short: "A skilled pair of hands for the small jobs on your list.",
    pricingModel: "hourly",
    aliases: ["handyman", "odd jobs", "fix", "repair"],
  }),

  /* ---------------- 05 Appliance & Utility Care ---------------- */
  S({
    slug: "ac-service",
    name: "AC Service",
    category: "appliance-care",
    subgroup: "cooling",
    bind: ["ac-service"],
    short: "AC maintenance, gas refill and repair.",
    pricingModel: "fixed",
    aliases: ["ac", "air conditioner", "aircon", "split ac", "window ac", "cooling", "gas refill"],
    includes: ["Inspection and servicing of the unit", "Work agreed with you during the visit"],
    excludes: ["Spare parts and refrigerant gas", "Wall or civil work"],
    prepare: [
      "Keep the indoor unit reachable — a stool or ladder helps.",
      "Make sure the outdoor unit can be reached safely.",
    ],
  }),
  S({
    slug: "ac-cleaning",
    name: "AC Cleaning",
    category: "appliance-care",
    subgroup: "cooling",
    short: "Filter, coil and drain cleaning for better cooling and air.",
    pricingModel: "per-unit",
    unit: "AC",
    aliases: ["ac cleaning", "ac wash", "jet wash", "filter"],
  }),
  S({
    slug: "ac-repair",
    name: "AC Repair",
    category: "appliance-care",
    subgroup: "cooling",
    short: "Diagnosis and repair for cooling, noise, leaks and power issues.",
    pricingModel: "inspection",
    aliases: ["ac repair", "ac not cooling", "ac leak", "compressor"],
  }),
  S({
    slug: "washing-machine-care",
    name: "Washing Machine Care",
    category: "appliance-care",
    subgroup: "utility",
    short: "Drum cleaning, descaling and servicing for washing machines.",
    pricingModel: "inspection",
    aliases: ["washing machine", "washer", "drum", "front load", "top load"],
  }),
  S({
    slug: "chimney-cleaning",
    name: "Chimney Cleaning",
    category: "appliance-care",
    subgroup: "kitchen",
    short: "Filter and hood degreasing for a kitchen chimney that pulls well.",
    pricingModel: "fixed",
    aliases: ["chimney", "hood", "exhaust", "kitchen chimney"],
  }),
  S({
    slug: "geyser-service",
    name: "Geyser Service",
    category: "appliance-care",
    subgroup: "utility",
    short: "Descaling, servicing and repair for water heaters.",
    pricingModel: "inspection",
    aliases: ["geyser", "water heater", "heater", "boiler"],
  }),
  S({
    slug: "small-appliance-care",
    name: "Microwave / Small Appliance Care",
    category: "appliance-care",
    subgroup: "kitchen",
    short: "Cleaning and care for microwaves, ovens and countertop appliances.",
    pricingModel: "per-unit",
    unit: "appliance",
    aliases: ["microwave", "oven", "otg", "toaster", "mixer", "small appliance"],
  }),
  S({
    slug: "appliance-installation",
    name: "Appliance Installation",
    category: "appliance-care",
    subgroup: "utility",
    short: "Installation and setup for new home appliances.",
    pricingModel: "per-unit",
    unit: "appliance",
    aliases: ["installation", "install", "setup", "new appliance"],
  }),

  /* ---------------- 06 Specialized Care ---------------- */
  S({
    slug: "pest-control",
    name: "Pest Control",
    category: "specialized-care",
    bind: ["pest-control"],
    short: "Cockroach, termite and general pest treatment.",
    pricingModel: "fixed",
    aliases: ["pest", "cockroach", "termite", "ants", "bed bugs", "rodent", "mosquito"],
    includes: ["Treatment of the areas agreed with you", "Guidance on precautions after treatment"],
    excludes: ["Structural repairs to seal entry points", "Removal of dead pests after the visit"],
    prepare: [
      "Cover or store food, utensils and pet bowls.",
      "Plan for children and pets to stay out of treated areas as advised.",
    ],
  }),
  S({
    slug: "plant-care",
    name: "Plant Care",
    category: "specialized-care",
    bind: ["plant-care"],
    short: "Watering, pruning, repotting and a plant health check.",
    pricingModel: "fixed",
    aliases: ["plants", "garden", "gardener", "gardening", "repotting", "mali"],
    includes: ["Watering and pruning", "Repotting as agreed", "A plant health check"],
    excludes: ["Pots, soil and plants", "Landscaping or lawn laying"],
  }),
  S({
    slug: "facade-cleaning",
    name: "Facade Cleaning",
    category: "specialized-care",
    bind: ["fasade-cleaning", "facade-cleaning"],
    short: "Exterior facade cleaning for buildings and apartments.",
    pricingModel: "fixed",
    aliases: ["facade", "fasade", "exterior", "building", "elevation"],
    includes: ["Cleaning of the exterior areas agreed with you"],
    excludes: ["Painting or repairs to the facade"],
  }),
  S({
    slug: "sanitization",
    name: "Sanitization",
    category: "specialized-care",
    short: "Whole-home disinfection of high-touch surfaces and rooms.",
    pricingModel: "area",
    unit: "sq. ft.",
    aliases: ["sanitize", "sanitise", "disinfection", "disinfect"],
  }),
  S({
    slug: "water-tank-cleaning",
    name: "Water Tank Cleaning",
    category: "specialized-care",
    short: "Draining, scrubbing and disinfection for overhead and underground tanks.",
    pricingModel: "per-unit",
    unit: "tank",
    aliases: ["tank", "water tank", "sump", "overhead tank"],
  }),
  S({
    slug: "specialized-surface-care",
    name: "Specialized Surface Care",
    category: "specialized-care",
    short: "Care for marble, wood, stone and other delicate surfaces.",
    pricingModel: "inspection",
    aliases: ["marble polish", "wood polish", "stone", "granite"],
  }),

  /* ---------------- 07 Laundry & Fabric Care ---------------- */
  S({
    slug: "laundry",
    name: "Laundry",
    category: "laundry-fabric",
    bind: ["laundry"],
    short: "Wash, dry and fold, returned fresh.",
    pricingModel: "fixed",
    aliases: ["laundry", "wash", "washing", "clothes", "dhobi"],
    includes: ["Washing and drying", "Folding"],
    excludes: ["Dry-clean-only garments", "Guaranteed removal of set-in stains"],
  }),
  S({
    slug: "washing-assistance",
    name: "Washing Assistance",
    category: "laundry-fabric",
    short: "Help running loads in your own machine — sorting, washing and drying.",
    pricingModel: "hourly",
    aliases: ["washing", "machine wash", "clothes washing"],
  }),
  S({
    slug: "steam-ironing",
    name: "Steam Ironing",
    category: "laundry-fabric",
    short: "Steam pressing for shirts, sarees, suits and delicate fabrics.",
    pricingModel: "per-unit",
    unit: "garment",
    aliases: ["steam press", "steam iron", "saree", "suit"],
  }),
  S({
    slug: "curtain-care",
    name: "Curtain Care",
    category: "laundry-fabric",
    short: "Curtains taken down, cleaned and re-hung.",
    pricingModel: "per-unit",
    unit: "panel",
    aliases: ["curtains", "drapes", "blinds cleaning"],
  }),
  S({
    slug: "fabric-upholstery-care",
    name: "Fabric / Upholstery Care",
    category: "laundry-fabric",
    short: "Cleaning for cushions, covers, rugs and upholstered pieces.",
    pricingModel: "per-unit",
    unit: "item",
    aliases: ["fabric", "upholstery", "cushion", "covers"],
  }),

  /* ---------------- 08 Vehicle Care ---------------- */
  S({
    slug: "car-surface-cleaning",
    name: "Car Surface Cleaning",
    category: "vehicle-care",
    bind: ["car-surface-cleaning"],
    short: "Exterior wash and polish with an interior vacuum, at your doorstep.",
    pricingModel: "fixed",
    aliases: ["car", "car wash", "vehicle", "car cleaning", "wash"],
    includes: ["Exterior wash and wipe-down", "Interior vacuum"],
    excludes: ["Engine bay cleaning", "Paint correction or scratch removal"],
  }),
  S({
    slug: "car-interior-cleaning",
    name: "Car Interior Cleaning",
    category: "vehicle-care",
    short: "Seats, mats, dashboard and cabin cleaned in detail.",
    pricingModel: "fixed",
    aliases: ["car interior", "seats", "dashboard", "cabin"],
  }),
  S({
    slug: "car-deep-cleaning",
    name: "Car Deep Cleaning",
    category: "vehicle-care",
    short: "Inside and out — a thorough reset for your car.",
    pricingModel: "package",
    aliases: ["car deep clean", "full car", "car spa"],
  }),
  S({
    slug: "bike-cleaning",
    name: "Bike Cleaning",
    category: "vehicle-care",
    short: "Wash and wipe-down for scooters and motorcycles.",
    pricingModel: "fixed",
    aliases: ["bike", "scooter", "motorcycle", "two wheeler"],
  }),
  S({
    slug: "vehicle-detailing",
    name: "Vehicle Detailing",
    category: "vehicle-care",
    short: "Detailing for paint, glass and interiors.",
    pricingModel: "package",
    aliases: ["detailing", "polish", "wax", "ceramic"],
  }),

  /* ---------------- 09 Beauty (general, live) ---------------- */
  S({
    slug: "salon-at-home",
    audiences: ALL_AUDIENCES,
    name: "Salon at Home",
    category: "beauty",
    bind: ["salon-at-home"],
    short: "Haircut, grooming and beauty services at your doorstep.",
    pricingModel: "fixed",
    aliases: ["salon", "beauty", "parlour", "parlor", "haircut", "grooming", "beautician"],
    includes: ["The beauty or grooming services you choose for the visit"],
    excludes: ["Services not agreed at the start of the visit"],
  }),

  /* ---------------- 10 Senior Care ---------------- */
  ...(
    [
      ["home-visit-support", "Home Visit Support", "Scheduled visits to check in and help around the home."],
      ["daily-assistance", "Daily Assistance", "Help with everyday routines, chores and errands."],
      ["companion-support", "Companion Support", "Warm company for conversation, walks and hobbies."],
      ["hospital-companion", "Hospital Companion", "Someone by their side for hospital visits and waiting time."],
      ["medicine-pickup", "Medicine Pickup", "Prescriptions picked up from the pharmacy and delivered home."],
      ["appointment-assistance", "Appointment Assistance", "Accompanied travel to and from appointments."],
      ["grocery-assistance", "Grocery Assistance", "Grocery runs and help putting things away."],
      ["senior-wellness-support", "Senior Wellness Support", "Gentle activity, routines and wellbeing support at home."],
    ] as const
  ).map(([slug, name, short]) =>
    S({
      slug,
      name,
      category: "senior-care",
      short,
      pricingModel: "hourly",
      aliases: ["senior", "elderly", "parents", "old age", "elder care"],
    }),
  ),

  /* ---------------- 11 Pet Care ---------------- */
  S({ slug: "pet-walking", name: "Pet Walking", category: "pet-care", short: "Daily walks at your pet's pace.", pricingModel: "hourly", aliases: ["dog walking", "walk", "dog"] }),
  S({ slug: "pet-feeding", name: "Pet Feeding", category: "pet-care", short: "Meals and fresh water on schedule while you are out.", pricingModel: "fixed", aliases: ["feeding", "cat", "dog"] }),
  S({ slug: "pet-sitting", name: "Pet Sitting", category: "pet-care", short: "Company and care at home while you are away.", pricingModel: "hourly", aliases: ["sitter", "pet sitter", "boarding"] }),
  S({ slug: "pet-cleaning", name: "Pet Cleaning", category: "pet-care", short: "Bath and clean-up for a fresh, happy pet.", pricingModel: "fixed", aliases: ["pet bath", "dog bath"] }),
  S({ slug: "basic-pet-grooming", name: "Basic Pet Grooming", category: "pet-care", short: "Brushing, nail trimming and tidy-up grooming.", pricingModel: "fixed", aliases: ["grooming", "pet grooming", "nail trim"] }),
  S({ slug: "vet-visit-assistance", name: "Vet Visit Assistance", category: "pet-care", short: "Accompanied trips to and from the vet.", pricingModel: "hourly", aliases: ["vet", "veterinary"] }),
  S({ slug: "pet-care-visits", name: "Pet Care Visits", category: "pet-care", short: "Drop-in visits for feeding, play and a quick check.", pricingModel: "fixed", aliases: ["drop in", "pet visit"] }),

  /* ---------------- 12 Executive & Concierge ---------------- */
  S({ slug: "driver-on-demand", name: "Driver On Demand", category: "executive-concierge", short: "A driver for your car, when you need one.", pricingModel: "hourly", aliases: ["driver", "chauffeur", "drive"] }),
  S({ slug: "personal-driver", name: "Personal Driver", category: "executive-concierge", short: "A dedicated driver for the day or a regular schedule.", pricingModel: "package", aliases: ["driver", "chauffeur", "monthly driver"] }),
  S({ slug: "office-assistant", name: "Office Assistant", category: "executive-concierge", short: "Help with admin, filing and small office tasks.", pricingModel: "hourly", aliases: ["assistant", "office", "admin"] }),
  S({ slug: "errand-runner", name: "Errand Runner", category: "executive-concierge", short: "Queues, pickups and everyday errands handled for you.", pricingModel: "hourly", aliases: ["errand", "runner", "tasks"] }),
  S({ slug: "document-pickup-drop", name: "Document Pickup & Drop", category: "executive-concierge", short: "Documents picked up and delivered across the city.", pricingModel: "fixed", aliases: ["document", "courier", "papers", "delivery"] }),
  S({ slug: "grocery-essentials-pickup", name: "Grocery / Essentials Pickup", category: "executive-concierge", short: "Groceries and essentials picked up from your store.", pricingModel: "fixed", aliases: ["grocery", "essentials", "shopping", "pickup"] }),
  S({ slug: "home-concierge", name: "Home Concierge", category: "executive-concierge", short: "One point of contact to coordinate help around your home.", pricingModel: "quote", aliases: ["concierge", "coordinator"] }),
  S({ slug: "personal-assistance", name: "Personal Assistance", category: "executive-concierge", short: "Flexible personal help for your day.", pricingModel: "hourly", aliases: ["personal assistant", "pa", "assistance"] }),

  /* ---------------- 13 Special & Future ---------------- */
  S({ slug: "home-move-assistance", name: "Home Move Assistance", category: "special-services", short: "Help coordinating and handling every step of a home move.", pricingModel: "quote", aliases: ["move", "relocation", "shifting"] }),
  S({ slug: "home-setup-assistance", name: "Home Setup Assistance", category: "special-services", short: "Unpacking, arranging and setting up your new home.", pricingModel: "quote", aliases: ["setup", "unpacking", "new home"] }),
  S({ slug: "rental-turnover-services", name: "Rental Turnover Services", category: "special-services", short: "Cleaning and resets between tenants or guests.", pricingModel: "package", aliases: ["rental", "airbnb", "tenant", "turnover"] }),
  S({ slug: "property-care-visits", name: "Property Care Visits", category: "special-services", short: "Regular check-ins on a property you do not live in.", pricingModel: "package", aliases: ["property", "vacant", "nri"] }),
  S({ slug: "vacation-home-check", name: "Vacation Home Check", category: "special-services", short: "Your home looked in on while you travel.", pricingModel: "fixed", aliases: ["vacation", "travel", "away"] }),
  S({ slug: "custom-service-request", name: "Custom Service Request", category: "special-services", short: "Need something not listed? Tell us and we will scope it.", pricingModel: "quote", aliases: ["custom", "other", "request", "something else"] }),
];

/* ------------------------------------------------------------------ */
/* Beauty — audience-based structure (bookable once admin enables).   */
/* ------------------------------------------------------------------ */

export const AUDIENCES: { id: Audience; name: string; hint: string }[] = [
  { id: "women", name: "Women", hint: "Hair, skin, nails, makeup & more" },
  { id: "men", name: "Men", hint: "Haircuts, beard, skin & grooming" },
  { id: "girls", name: "Girls", hint: "Kids & teens" },
  { id: "boys", name: "Boys", hint: "Kids & teens" },
  { id: "senior-women", name: "Senior Women", hint: "Gentle care & relaxation" },
  { id: "senior-men", name: "Senior Men", hint: "Gentle care & grooming" },
];

export const BEAUTY_TYPES: { id: BeautyType; name: string }[] = [
  { id: "hair", name: "Hair" },
  { id: "skin", name: "Skin" },
  { id: "waxing", name: "Waxing & Threading" },
  { id: "nails", name: "Nails" },
  { id: "makeup", name: "Makeup" },
  { id: "grooming", name: "Grooming" },
  { id: "spa", name: "Spa & Massage" },
  { id: "bridal", name: "Bridal & Wedding" },
];

/**
 * One service per treatment, with audience eligibility — not one record per
 * audience. The six audience pages filter by `audiences`; the backend config
 * (catalogConfig.audiences) overrides these defaults once a service is live.
 */
type BeautyRow = [slug: string, name: string, type: BeautyType, short: string, audiences: Audience[], model?: "fixed" | "package"];

const BEAUTY: BeautyRow[] = [
  ["haircut-styling", "Haircut & Styling", "hair", "Cuts and styling at home, for every age.", ALL_AUDIENCES],
  ["hair-styling", "Hair Styling", "hair", "Braids, buns and styles for school and events.", ["girls", "boys"]],
  ["occasion-styling", "Occasion Styling", "hair", "Styling for birthdays, weddings and functions.", ["girls"]],
  ["hair-colour", "Hair Colour", "hair", "Global colour, highlights, root touch-ups and grey coverage.", ["women", "men"]],
  ["hair-treatments", "Hair Treatments", "hair", "Spa and nourishing treatments for healthier hair.", ["women"]],
  ["facial-skin", "Facial & Skin", "skin", "Facials matched to your skin type.", ["women", "men"]],
  ["cleanup", "Cleanup", "skin", "A quick refresh for clearer skin.", ["women", "men"]],
  ["bleach-detan", "Bleach & De-Tan", "skin", "Even out tone and lift tan.", ["women", "men"]],
  ["threading", "Threading", "waxing", "Brows, upper lip and face threading.", ["women"]],
  ["waxing", "Waxing", "waxing", "Arms, legs and full-body waxing options.", ["women"]],
  ["manicure-pedicure", "Manicure & Pedicure", "nails", "Hand and foot care.", ["women", "men", "senior-women", "senior-men"]],
  ["nails", "Nails", "nails", "Nail art, extensions and polish.", ["women"]],
  ["makeup", "Makeup", "makeup", "Party and occasion makeup at home.", ["women"]],
  ["draping", "Draping", "makeup", "Saree and dupatta draping for any occasion.", ["women"]],
  ["bridal-wedding", "Bridal & Wedding", "bridal", "Bridal and wedding-party looks, planned with you.", ["women"], "package"],
  ["spa-massage", "Spa & Massage", "spa", "Relaxing massage and body care.", ["women"]],
  ["beard-shaving", "Beard & Shaving", "grooming", "Beard shaping, trims and clean shaves.", ["men", "senior-men"]],
  ["head-massage", "Head Massage", "spa", "A relaxing head and shoulder massage.", ["men"]],
  ["grooming-packages", "Grooming Packages", "grooming", "Haircut, beard and skin care together.", ["men"], "package"],
  ["gentle-grooming", "Gentle Grooming", "grooming", "Age-appropriate grooming basics for kids and teens.", ["girls", "boys"]],
  ["gentle-skin-care", "Gentle Skin Care", "skin", "Mild, soothing skin care.", ["senior-women", "senior-men"]],
  ["head-foot-care", "Head & Foot Care", "spa", "Soothing head and foot massage.", ["senior-women"]],
  ["relaxation", "Relaxation", "spa", "Gentle relaxation therapies.", ["senior-women", "senior-men"]],
];

const BEAUTY_SERVICES: ServiceDef[] = BEAUTY.map(([slug, name, type, short, audiences, model]) =>
  S({
    slug,
    // Backend slug an admin creates to make this service bookable.
    bind: [`beauty-${slug}`],
    name,
    category: "beauty",
    subgroup: type,
    short,
    pricingModel: model ?? "fixed",
    audiences,
    beautyType: type,
    aliases: [...audiences.map((a) => AUDIENCES.find((x) => x.id === a)!.name.toLowerCase()), type, "beauty", "salon", "parlour"],
  }),
);

/** Kids' appointments: customer guidance, shown when a kids audience is selected. */
export const KIDS_GUIDANCE = "A parent or guardian should be present during appointments for kids and teens.";

/**
 * Old one-record-per-audience URLs (/services/beauty/<audience>/<leaf>) → the
 * canonical service. Used for 308 redirects so no old link breaks.
 */
export const LEGACY_BEAUTY_LEAF: Record<string, string> = {
  hair: "haircut-styling",
  haircut: "haircut-styling",
  facial: "facial-skin",
  "facial-cleanup": "facial-skin",
  detan: "bleach-detan",
  styling: "hair-styling",
  "basic-grooming": "gentle-grooming",
};

export const SERVICE_DEFS: ServiceDef[] = [...SERVICES_CORE, ...BEAUTY_SERVICES];

/**
 * Services shown in a second category. They render the canonical card and link
 * to the canonical page, so there is exactly one detail page per service.
 */
export const CROSS_LISTINGS: CrossListing[] = [
  { ref: "laundry", category: "home-help", subgroup: "clothes" },
  { ref: "ironing-folding", category: "home-help", subgroup: "clothes" },
  { ref: "packing-unpacking", category: "event-occasion" },
  { ref: "home-setup-assistance", category: "event-occasion" },
  { ref: "fridge-cleaning", category: "appliance-care", subgroup: "kitchen" },
];

/** Hub page order for editorial rails (spec order). */
export const HUB_RAIL_ORDER: CategoryId[] = [
  "home-cleaning",
  "home-maintenance",
  "appliance-care",
  "laundry-fabric",
  "event-occasion",
  "specialized-care",
  "vehicle-care",
];

export function audienceName(id: Audience): string {
  return AUDIENCES.find((a) => a.id === id)?.name ?? id;
}

export function isAudience(value: string): value is Audience {
  return AUDIENCES.some((a) => a.id === value);
}

/** "All ages", or "Women · Men" — short eligibility label for cards and search. */
export function audienceSummary(audiences: Audience[]): string | null {
  if (!audiences.length) return null;
  if (audiences.length === AUDIENCES.length) return "All ages";
  return audiences.map(audienceName).join(" · ");
}
