import prisma from "../lib/prisma";

/**
 * AI conversation persistence — PostgreSQL is the source of truth for chat history.
 * Every turn (user message + assistant reply) is stored; the rule-based replies are
 * generated by customerAiService, this layer only persists/loads them.
 */
export class AiConversationService {
  /** Append a user+assistant turn, creating the conversation if needed. Returns the id. */
  async appendTurn(
    userId: string,
    conversationId: string | undefined,
    userText: string,
    assistantText: string,
  ): Promise<string> {
    let convId: string | undefined = conversationId;

    if (convId) {
      const owned = await prisma.aiConversation.findFirst({
        where: { id: convId, userId },
        select: { id: true },
      });
      if (!owned) convId = undefined; // not theirs (or deleted) → start fresh
    }

    if (!convId) {
      const conv = await prisma.aiConversation.create({
        data: { userId, title: userText.slice(0, 60) },
        select: { id: true },
      });
      convId = conv.id;
    }

    await prisma.aiMessage.createMany({
      data: [
        { conversationId: convId, role: "user", content: userText },
        { conversationId: convId, role: "assistant", content: assistantText },
      ],
    });
    await prisma.aiConversation.update({
      where: { id: convId },
      data: { updatedAt: new Date() },
    });
    return convId;
  }

  /** List the user's conversations (most-recent first) with a last-message preview. */
  async list(userId: string) {
    const rows = await prisma.aiConversation.findMany({
      where: { userId },
      orderBy: { updatedAt: "desc" },
      take: 30,
      include: { messages: { orderBy: { createdAt: "desc" }, take: 1 } },
    });
    return rows.map((c) => ({
      id: c.id,
      title: c.title,
      updatedAt: c.updatedAt,
      lastMessage: c.messages[0]?.content ?? null,
    }));
  }

  /** Full message list for one conversation (owner-checked). Null if not found/owned. */
  async messages(userId: string, conversationId: string) {
    const conv = await prisma.aiConversation.findFirst({
      where: { id: conversationId, userId },
      select: { id: true, title: true },
    });
    if (!conv) return null;
    const msgs = await prisma.aiMessage.findMany({
      where: { conversationId },
      orderBy: { createdAt: "asc" },
      select: { id: true, role: true, content: true, createdAt: true },
    });
    return { id: conv.id, title: conv.title, messages: msgs };
  }

  /** The user's most recent conversation (to reload on app open). */
  async latest(userId: string) {
    const conv = await prisma.aiConversation.findFirst({
      where: { userId },
      orderBy: { updatedAt: "desc" },
      select: { id: true },
    });
    return conv ? this.messages(userId, conv.id) : null;
  }

  /** Delete a conversation (owner-checked). */
  async remove(userId: string, conversationId: string): Promise<boolean> {
    const conv = await prisma.aiConversation.findFirst({
      where: { id: conversationId, userId },
      select: { id: true },
    });
    if (!conv) return false;
    await prisma.aiConversation.delete({ where: { id: conversationId } });
    return true;
  }
}

export const aiConversationService = new AiConversationService();
